const fs = require('fs');

module.exports = function(append) {
  append(`## invoices.json

### Schema
- Top-level Container: Object with keys:
  - \`invoices\`: Array of Invoice records (Required)
  - \`lastInvoiceSeq\`: Number (Required). Sequential counter for invoice numbering.
  - \`lastUpdated\`: String ISO 8601 timestamp (Required)
- Record Fields:
  - \`id\`: String (Required). Primary Key. Format: \`INV-XXXXXX\` via \`uid('INV')\`.
  - \`invoiceNumber\`: String (Required). GST Rule 46 sequential invoice number (e.g. \`INV-/2026-27/0001\`). Generated by:
    \`\`\`javascript
    // server.js:1882-1896
    const prefix = settings.invoicePrefix || 'INV-';
    const year = new Date().getFullYear();
    const nextYear = String(year + 1).slice(-2);
    const fy = \`\${year}-\${nextYear}\`;
    const seq = (d.lastInvoiceSeq || 0) + 1;
    d.lastInvoiceSeq = seq;
    const invoiceNumber = \`\${prefix}/\${fy}/\${String(seq).padStart(4, '0')}\`;
    \`\`\`
  - \`customerName\`: String (Required). Customer name.
  - \`customer\`: Object (Required). Embedded snapshot of customer details (\`name\`, \`gstin\`, \`pan\`, \`address\`, \`city\`, \`state\`, \`stateCode\`).
  - \`supplyType\`: String (Required). Tax regime: \`'intra'\` (CGST + SGST split) or \`'inter'\` (IGST full).
  - \`date\`: String (Required). \`YYYY-MM-DD\`.
  - \`items\`: Array of LineItem records (Required, non-empty):
    - LineItem Fields:
      - \`productId\`: String (Required). References \`products.json\`. Product must have variants configured (\`server.js:1807\`).
      - \`variantId\`: String (Required). Primary key of product variation.
      - \`name\`: String (Required). Formatted item label with packaging unit.
      - \`hsn_sac\`: String (Optional, default \`'3004'\`).
      - \`qty\`: Number (Required). Strictly positive finite number (\`server.js:1801\`). Deducted from variant stock.
      - \`rate\`: Number (Required). Unit selling price.
      - \`gst_rate\`: Number (Required). Tax percentage (0, 5, 12, 18, 28).
      - \`taxableAmount\`: Number (Required). Float: \`qty * rate\`.
      - \`cgst\`: Number (Required if intra). \`taxableAmount * (gst_rate / 2) / 100\`.
      - \`sgst\`: Number (Required if intra). \`taxableAmount * (gst_rate / 2) / 100\`.
      - \`igst\`: Number (Required if inter). \`taxableAmount * gst_rate / 100\`.
      - \`total\`: Number (Required). Line total with tax.
  - \`subtotal\`: Number (Required). Sum of line taxable amounts.
  - \`cgstTotal\`: Number (Optional).
  - \`sgstTotal\`: Number (Optional).
  - \`igstTotal\`: Number (Optional).
  - \`totalTax\`: Number (Required). Sum of all tax components.
  - \`grandTotal\`: Number (Required). Final invoice payable amount.
  - \`status\`: String (Required). Values: \`'paid'\`, \`'pending'\`, \`'overdue'\`, \`'cancelled'\`.
  - \`paymentMethod\`: String (Optional).
  - \`auditCorrelationId\`: String (Required). Shared correlation ID: \`AUD-YYYY-NNNNNN\`.
  - \`notes\`: String (Optional).
  - \`createdAt\`: String (Required). ISO 8601 timestamp.
  - \`updatedAt\`: String (Optional). ISO 8601 timestamp.
- Foreign Keys / References:
  - References \`products.json\` (\`items[].productId\`, \`items[].variantId\`): Strictly validated at line \`server.js:1807\`. Rejects unvarianted products with HTTP 400.
  - References \`customers.json\` (\`customer.id\`): Optional link; customer profile is denormalized directly into invoice.

### Where it's written
1. **Startup Normalizer: \`normalizeHistoricalAuditData()\` at \`server.js:470\`**
   - Populates missing correlation IDs.
   - **Atomicity**: Atomic via \`writeJSONAtomic\`.
2. **Update Invoice: \`PUT /api/invoices/:id\` at \`server.js:1907\`**
   - **Trigger**: User edits invoice status or payment notes.
   - **Atomicity**: **NON-ATOMIC**. Quoted from code:
     \`\`\`javascript
     // server.js:1907
     writeJSON(INVOICES_FILE, d);
     \`\`\`
     Calls \`writeJSON\` (\`fs.writeFileSync\`).
3. **Create Invoice: \`POST /api/invoices\` at \`server.js:2118\`**
   - **Trigger**: User generates and saves commercial invoice.
   - **Fields Changed & Transformation Logic**:
     Validates stock sufficiency, deducts \`variant.stock -= item.qty\`, increments \`d.lastInvoiceSeq\`, formats Rule 46 number, pushes invoice object.
   - **Atomicity**: Protected by \`withInventoryLock\`. Written via \`writeJSONAtomic\`.
4. **Cancel Invoice (No Restock): \`DELETE /api/invoices/:id\` at \`server.js:2149\`**
   - **Trigger**: User cancels invoice without restock.
   - **Fields Changed**: Sets \`inv.status = 'cancelled'\`. Soft delete!
   - **Atomicity**: Atomic via \`writeJSONAtomic\`.
5. **Cancel Invoice (With Restock): \`DELETE /api/invoices/:id?restock=true\` at \`server.js:2251\`**
   - **Trigger**: User cancels invoice with restock checked.
   - **Fields Changed**: Sets \`inv.status = 'cancelled'\`, restores \`variant.stock += item.qty\`. Soft delete!
   - **Atomicity**: Atomic via \`writeJSONAtomic\`. Not lock-protected.
6. **System Reset: \`POST /api/system/reset-data\` at \`server.js:2339\`**
   - Empties collection: \`{ invoices: [], lastInvoiceSeq: 0, lastUpdated: now }\`.
   - **Atomicity**: Atomic via \`writeJSONAtomic\`.
7. **Legacy Import: \`POST /api/import-data\` at \`server.js:2496\`**
   - Overwrites store.
   - **Atomicity**: Non-atomic via \`writeJSON\`.
8. **Modular Import: \`POST /api/import-data/:section\` at \`server.js:2856\`**
   - Merges invoices and updates \`lastInvoiceSeq\`.
   - **Atomicity**: Atomic via \`writeJSONAtomic\`.

### Where it's read
- \`normalizeHistoricalAuditData()\` (\`server.js:446\`): Startup normalizer.
- \`GET /api/invoices\` (\`server.js:1787\`): Serves invoice register.
- \`POST /api/invoices\` (\`server.js:1793\`): Reads store to increment sequence.
- \`PUT /api/invoices/:id\` (\`server.js:1898\`): Finds invoice to update.
- \`DELETE /api/invoices/:id\` (\`server.js:2160\`): Finds invoice to cancel.
- \`GET /api/raw-material-batches/:id/traceability\` (\`server.js:3687\`): Traces downstream invoices that consumed finished goods.
- \`GET /api/manufacturing-batches/:id/traceability\` (\`server.js:4678\`): Traces sales invoices billed from batch.
- \`GET /api/stats\` (\`server.js:5429\`): Computes total revenue and paid/pending balances.

### Full lifecycle
- **CREATE**: Created via \`POST /api/invoices\`. Deducts ready-to-sell packaged stock from \`products.json\`.
- **UPDATE**: Status changes (pending $\\rightarrow$ paid) via \`PUT /api/invoices/:id\`.
- **DELETE**: **SOFT DELETE**. Invoices are **NEVER spliced or removed** from \`invoices.json\`. They are flagged with \`status = 'cancelled'\` to preserve legal tax invoice sequence integrity required under GST regulations.
- **Audit Logging**: Creation logs \`INVENTORY_OUT\` to \`manufacturing_audit.json\` (\`server.js:2090\`). Cancellation does not emit a separate audit record.

### Cross-file transactions
Written in conjunction with \`products.json\`, \`finished_goods_transactions.json\`, and \`manufacturing_audit.json\`.
- **Order of Writes in \`POST /api/invoices\`**:
  1. \`finished_goods_transactions.json\` (\`server.js:1977\`)
  2. \`products.json\` (\`server.js:1987\`)
  3. \`manufacturing_audit.json\` (\`server.js:2090\`)
  4. \`invoices.json\` (\`server.js:2118\`)
- **Failure Risk**: Wrapped in \`withInventoryLock\`. If server crashes at step 2, stock is deducted in \`products.json\`, but invoice is missing from \`invoices.json\`.

### Known edge cases / validation gaps
- **Contradiction with Documentation**: Documentation states invoices can be deleted. In code, \`DELETE /api/invoices/:id\` only updates \`status = 'cancelled'\`; the record remains permanently in \`invoices.json\`.
- **Restock Concurrency Gap**: \`DELETE /api/invoices/:id?restock=true\` restores variant stock without acquiring \`withInventoryLock\`.

---

## notes.json

### Schema
- Top-level Container: Object with keys:
  - \`notes\`: String (Required, default \`""\`). Free-form scratchpad text.
- Foreign Keys / References: None. Completely decoupled utility store.

### Where it's written
1. **System Reset: \`POST /api/system/reset-data\` at \`server.js:2349\`**
   - Sets \`{ notes: '' }\`.
   - **Atomicity**: Atomic via \`writeJSONAtomic\`.
2. **Save Scratchpad Notes: \`POST /api/notes\` at \`server.js:5538\`**
   - **Trigger**: User types or saves notes in the floating scratchpad widget.
   - **Atomicity**: **NON-ATOMIC**. Quoted from code:
     \`\`\`javascript
     // server.js:5538
     fs.writeFileSync(NOTES_FILE, JSON.stringify({ notes }, null, 2));
     \`\`\`
     Direct synchronous overwrite.

### Where it's read
- \`GET /api/notes\` (\`server.js:5528\`): Returns scratchpad content.

### Full lifecycle
- **CREATE/UPDATE**: Overwrites the single \`notes\` string property.
- **DELETE**: Emptied on system reset.
- **Audit Logging**: None.

### Cross-file transactions
None. Single-store decoupled file.

### Known edge cases / validation gaps
- **Non-Atomic File Write**: Uses direct \`fs.writeFileSync\`. Interruption during write corrupts the file.

---

## settings.json

### Schema
- Top-level Container: Object with keys:
  - \`companyName\`: String
  - \`businessName\`: String
  - \`businessGSTIN\` / \`businessGstin\`: String. 15-character GST registration number.
  - \`businessPAN\` / \`businessPan\`: String. 10-character PAN.
  - \`businessState\`: String. State name.
  - \`businessStateCode\`: String. 2-digit GST state code (used for intra vs inter-state tax split).
  - \`businessAddress\`: String.
  - \`businessEmail\`: String.
  - \`businessPhone\`: String.
  - \`businessWebsite\`: String.
  - \`businessBankName\`: String.
  - \`businessBankAcc\`: String.
  - \`businessBankIFSC\`: String.
  - \`businessLogoBase64\`: String.
  - \`invoicePrefix\`: String (default \`'INV-'\`).
  - \`invoiceTerms\`: String. Default legal conditions.
  - \`invoiceNotes\`: String. Default footer note.
  - \`firstLaunchCompleted\`: Boolean.
  - \`userName\`: String.
  - \`apiKey\`: String. Gemini/OpenAI API key.
  - \`modelName\`: String.
- Foreign Keys / References:
  - Referenced by \`invoices.json\` during invoice number formatting (\`invoicePrefix\`) and state code comparison for GST splitting.

### Where it's written
1. **Update Settings: \`PUT /api/settings\` at \`server.js:2288\`**
   - **Trigger**: User updates business profile in Settings.
   - **Atomicity**: **NON-ATOMIC**. Quoted from code:
     \`\`\`javascript
     // server.js:2288
     writeJSON(SETTINGS_FILE, updated);
     \`\`\`
     Calls \`writeJSON\` (\`fs.writeFileSync\`).
2. **System Reset: \`POST /api/system/reset-data\` at \`server.js:2336\`**
   - Resets to factory default settings.
   - **Atomicity**: Atomic via \`writeJSONAtomic\`.
3. **Legacy Import: \`POST /api/import-data\` at \`server.js:2487\`**
   - Non-atomic via \`writeJSON\`.
4. **Modular Import: \`POST /api/import-data/:section\` at \`server.js:2922\`**
   - Atomic via \`writeJSONAtomic\`.

### Where it's read
- \`POST /api/invoices\` (\`server.js:1882\`): Reads \`invoicePrefix\` for sequence generation.
- \`GET /api/settings\` (\`server.js:2280\`): Serves settings to UI.
- \`GET /api/export-data\` (\`server.js:2371\`): Full backup export.
- \`POST /api/import-data\` & \`:section\` (\`server.js:2471\`, \`2592\`): Pre-import backup.
- \`POST /api/ai/invoke\` (\`server.js:5473\`): Reads \`apiKey\` and \`modelName\`.

### Full lifecycle
- **CREATE/UPDATE**: Overwrites profile object.
- **DELETE**: Emptied/reset to default object on factory reset.
- **Audit Logging**: None.

### Cross-file transactions
Independent store.

### Known edge cases / validation gaps
- **Contradiction with Documentation**: Settings updates are written with non-atomic \`writeJSON\` (\`fs.writeFileSync\`), contradicting docs claiming 100% atomic persistence.

---

## data/.version

### Schema
- Raw UTF-8 text file containing software version string (e.g. \`"3.1.0"\`).
- No JSON structure.

### Where it's written
1. \`main.js:49\`: Written upon Electron desktop app launch when comparing bundled data version against installed AppData version:
   \`\`\`javascript
   // main.js:49
   fs.writeFileSync(versionFile, CURRENT_RELEASE_VERSION, 'utf8');
   \`\`\`
2. \`server.js:2358\`: Written during factory reset:
   \`\`\`javascript
   // server.js:2358
   try { fs.writeFileSync(path.join(DATA_DIR, '.version'), '3.1.0', 'utf8'); } catch (_) {}
   \`\`\`
3. \`clean-data.js:94\`: Written during production data sanitization:
   \`\`\`javascript
   // clean-data.js:94
   fs.writeFileSync(path.join(dir, '.version'), '3.1.0', 'utf8');
   \`\`\`

### Where it's read
- \`main.js:23\`: Read on application launch to detect if bundled files need to be copied into \`%APPDATA%\\InvoiceWise\\InvoiceWiseData\`.

### Full lifecycle
- Overwritten on app upgrade or data sanitization. Never deleted.

### Cross-file transactions
Written alongside clean database resets.

### Known edge cases / validation gaps
- If \`.version\` is missing or corrupt, Electron treats the installation as fresh and overwrites AppData from bundled repository files (\`main.js:43\`).

---

## data/.inventory.lock

### Schema
- Empty filesystem lock token created via \`O_CREAT | O_EXCL\` (\`'wx'\` flag in Node.js \`fs.openSync\`).
- Contains no payload. Exists only as a filesystem-level synchronization primitive.

### Where it's written
1. **Acquire Lock: \`withInventoryLock()\` at \`server.js:94\`**
   - \`fs.openSync(lockFile, 'wx')\` creates the file exclusively.
2. **Stale Lock Cleanup: \`withInventoryLock()\` at \`server.js:102\`**
   - If lock is older than 15,000 ms, \`fs.unlinkSync(lockFile)\` forcibly unlinks the stale lock.
3. **Release Lock: \`withInventoryLock()\` at \`server.js:118\`**
   - Inside \`finally\` block, executes \`fs.unlinkSync(lockFile)\`.

### Where it's read
- Checked for existence via \`fs.openSync\` failure (\`EEXIST\`) and \`fs.statSync\` (\`server.js:100\`) to check \`mtimeMs\`.

### Full lifecycle
- Created at the start of critical inventory transactions (\`POST /api/invoices\`, \`POST /api/products/:id/fill-bottles\`). Deleted immediately upon completion.

### Cross-file transactions
Synchronizes all files touched during bottling runs and invoice creation.

### Known edge cases / validation gaps
- **Scope Limitation**: Only \`POST /api/invoices\` and \`POST /api/products/:id/fill-bottles\` are wrapped in \`withInventoryLock\`. Manufacturing commits, inward purchases, and variant deletions run without lock protection.

---

## data/pre_import_backup.json

### Schema
- Full multi-store JSON bundle containing:
  \`\`\`json
  {
    "backupDate": "ISO timestamp",
    "version": "3.1.0",
    "stores": {
      "settings": {},
      "products": [],
      "customers": [],
      "invoices": [],
      "raw_materials": [],
      "raw_material_batches": [],
      "recipes": [],
      "manufacturing_batches": [],
      "manufacturing_audit": [],
      "finished_goods": [],
      "raw_material_transactions": [],
      "finished_goods_transactions": []
    }
  }
  \`\`\`

### Where it's written
1. **Legacy Import Pre-backup: \`POST /api/import-data\` at \`server.js:2483\`**
   - Writes \`pre_import_backup.json\` using non-atomic \`writeJSON\`.
2. **Modular Import Pre-backup: \`POST /api/import-data/:section\` at \`server.js:2604-2605\`**
   - Writes timestamped backup \`pre_import_backup_\${Date.now()}.json\` and symlink/copy \`pre_import_backup.json\` using \`writeJSONAtomic\`.

### Where it's read
- Purged during system data reset (\`server.js:2355\`) and production data sanitizer (\`clean-data.js:71\`).

### Full lifecycle
- Created before any import mutation. Retained on disk until explicitly cleaned.

### Cross-file transactions
Reads all 12 operational data stores before modifying any target store.

### Known edge cases / validation gaps
- In legacy import (\`server.js:2483\`), if writing \`pre_import_backup.json\` fails or crashes, the import continues or throws without ensuring the backup is intact.

---
`);
};
