const fs = require('fs');

module.exports = function(append) {
  append(`## raw_material_batches.json

### Schema
- Top-level Container: Object with keys:
  - \`raw_material_batches\`: Array of Batch records (Required)
  - \`lastUpdated\`: String ISO 8601 timestamp (Required)
- Record Fields:
  - \`id\`: String (Required). Primary Key. Format: \`RMB-YYYY-NNNN\` (4-digit zero-padded sequence). Generated by:
    \`\`\`javascript
    // server.js:244-257
    function generateRMBatchId() {
      const year = new Date().getFullYear();
      const prefix = \`RMB-\${year}-\`;
      const rmbData = readJSON(RAW_MATERIAL_BATCHES_FILE) || { raw_material_batches: [] };
      let maxSeq = 0;
      (rmbData.raw_material_batches || []).forEach(b => {
        const id = b.id || b.batchId;
        if (typeof id === 'string' && id.startsWith(prefix)) {
          const num = parseInt(id.replace(prefix, ''), 10);
          if (!isNaN(num) && num > maxSeq) maxSeq = num;
        }
      });
      return \`\${prefix}\${String(maxSeq + 1).padStart(4, '0')}\`;
    }
    \`\`\`
  - \`batchId\`: String (Required alias). Exact duplicate of \`id\`.
  - \`rawMaterialId\`: String (Required). Foreign Key referencing \`raw_materials.json\`.
  - \`rawMaterialName\`: String (Optional). Denormalized material name.
  - \`supplierBatchNumber\`: String (Optional, default \`'-'\`). Vendor/supplier lot tracking number.
  - \`lotNumber\`: String (Optional alias). Synced to \`supplierBatchNumber\`.
  - \`originalQuantity\`: Number (Required). Float. Initial quantity at inward purchase.
  - \`quantity\`: Number (Required alias). Synced to \`originalQuantity\`.
  - \`remainingQuantity\`: Number (Required). Float. Current available quantity. Decremented by consumption; incremented by reversal.
  - \`remainingQty\`: Number (Required alias). Mirrored to \`remainingQuantity\`.
  - \`unit\`: String (Required). Unit of measurement. Mirrored from parent raw material.
  - \`cost_per_unit\`: Number (Optional, default \`0\`). Cost per unit in INR.
  - \`vendorPrice\`: Number (Optional alias). Computed as \`cost_per_unit * quantity\`.
  - \`vendorName\`: String (Optional). Supplier / vendor name.
  - \`vendorId\`: String (Optional). Vendor identifier if chosen.
  - \`supplier\`: String (Optional alias). Synced to \`vendorName\`.
  - \`vendorGstNumber\`: String (Optional). Supplier GSTIN.
  - \`vendorBillingRef\`: String (Optional). Inward invoice / challan number.
  - \`purchaseDate\`: String (Optional). Inward date string.
  - \`receivedDate\`: String (Optional). Received date string.
  - \`expiryDate\`: String (Optional). Batch expiry date.
  - \`storageLocation\`: String (Optional). Warehouse bin/rack location.
  - \`coaStatus\`: String (Optional, default \`'PASSED'\`). Certificate of Analysis status.
  - \`status\`: String (Required). Values: \`'ACTIVE'\` (if \`remainingQuantity > 0\`) or \`'CONSUMED'\` (if \`remainingQuantity <= 0\`).
  - \`auditCorrelationId\`: String (Optional). Unique correlation ID (\`AUD-YYYY-NNNNNN\`).
  - \`notes\`: String (Optional).
  - \`createdAt\`: String (Required). ISO 8601 timestamp.
  - \`updatedAt\`: String (Optional). ISO 8601 timestamp.
- Foreign Keys / References:
  - References \`raw_materials.json\` (\`rawMaterialId\`): Must match an existing material ID. Validated at batch creation (\`server.js:3315\`).
  - Inward reference from \`raw_material_transactions.json\` (\`allocations[].batchId\`): Records which batches supplied items.

### Where it's written
1. **Startup Reconciler: \`reconcileRawMaterialBatches()\` at \`server.js:367\`**
   - **Trigger**: Server launch execution (line 478).
   - **Fields Changed & Transformation Logic**:
     Normalizes field aliases (\`remainingQuantity\`, \`originalQuantity\`, \`unit\`, \`rawMaterialName\`, \`status\`). If parent stock exceeds active batches sum, synthesizes a baseline opening stock batch (\`server.js:320-350\`).
   - **Atomicity**: Atomic via \`writeJSONAtomic\`.

2. **Variant Deletion (Reversal): \`DELETE /api/products/:productId/variants/:variantId\` at \`server.js:1184\`**
   - **Trigger**: Variant deleted with \`action: 'REVERSE'\`.
   - **Fields Changed & Transformation Logic**:
     \`\`\`javascript
     // server.js:1068-1075
     const batch = (rmbData.raw_material_batches || []).find(b => b.id === alloc.batchId || b.batchId === alloc.batchId);
     if (batch) {
       batch.remainingQuantity = parseFloat(((batch.remainingQuantity !== undefined ? batch.remainingQuantity : (batch.quantity || 0)) + restoreToAlloc).toFixed(6));
       batch.remainingQty = batch.remainingQuantity;
       if (batch.status === 'CONSUMED' || batch.status === 'DEPLETED') {
         batch.status = 'ACTIVE';
       }
       batch.updatedAt = timestamp;
     }
     \`\`\`
   - **Atomicity**: Atomic via \`writeJSONAtomic\`. Not wrapped in mutex lock.

3. **Bottling / Packaging Run: \`POST /api/products/:id/fill-bottles\` at \`server.js:1469\`**
   - **Trigger**: Bottling run packaging deduction.
   - **Fields Changed & Transformation Logic**:
     Allocates \`packagingNeeded\` across active batches in FIFO or preferred vendor order:
     \`\`\`javascript
     // server.js:1406-1413
     batch.remainingQuantity = parseFloat((curBatchRem - takeQty).toFixed(6));
     batch.remainingQty = batch.remainingQuantity;
     if (batch.remainingQuantity <= 0) {
       batch.status = 'CONSUMED';
     }
     batch.updatedAt = timestamp;
     \`\`\`
   - **Atomicity**: Protected by \`withInventoryLock\`. Written via \`writeJSONAtomic\`.

4. **System Data Reset: \`POST /api/system/reset-data\` at \`server.js:2347\`**
   - **Trigger**: User resets all data in Settings.
   - **Fields Changed**: Empties array to \`{ raw_material_batches: [], lastUpdated: new Date().toISOString() }\`.
   - **Atomicity**: Atomic via \`writeJSONAtomic\`.

5. **Create Opening Batch on RM Creation: \`POST /api/raw-materials\` at \`server.js:3052\`**
   - **Trigger**: User creates raw material with initial opening stock > 0.
   - **Fields Changed**: Pushes new batch with ID \`generateRMBatchId()\`, \`originalQuantity = initialStock\`, \`remainingQuantity = initialStock\`, \`status = 'ACTIVE'\`.
   - **Atomicity**: Atomic via \`writeJSONAtomic\`.

6. **Cascade Unit & Name Update: \`PUT /api/raw-materials/:id\` at \`server.js:3155\`**
   - **Trigger**: User edits RM unit or name.
   - **Fields Changed & Transformation Logic**:
     \`\`\`javascript
     // server.js:3146-3151
     rmbData.raw_material_batches.forEach(b => {
       if (b.rawMaterialId === req.params.id) {
         if (unitChanged) b.unit = item.unit;
         if (nameChanged) b.rawMaterialName = item.name;
       }
     });
     \`\`\`
   - **Atomicity**: Atomic via \`writeJSONAtomic\`.

7. **Delete Raw Material Cascade: \`DELETE /api/raw-materials/:id\` at \`server.js:3293\`**
   - **Trigger**: User deletes raw material.
   - **Fields Changed**: Slices out all batches matching \`rawMaterialId\`:
     \`\`\`javascript
     // server.js:3290-3292
     rmbData.raw_material_batches = rmbData.raw_material_batches.filter(b => b.rawMaterialId !== req.params.id);
     \`\`\`
   - **Atomicity**: Atomic via \`writeJSONAtomic\`.

8. **Add Stock / Inward Lot: \`POST /api/raw-materials/:id/add-stock\` at \`server.js:3447\`**
   - **Trigger**: User records an inward purchase lot.
   - **Fields Changed & Transformation Logic**:
     Generates batch ID via \`generateRMBatchId()\`, pushes new record with \`originalQuantity = qty\`, \`remainingQuantity = qty\`, \`status = 'ACTIVE'\`, supplier lot metadata, COA status, and storage location.
   - **Atomicity**: Atomic via \`writeJSONAtomic\`. Not lock-protected.

9. **Delete Vendor Lot: \`POST /api/raw-materials/:id/delete-vendor\` at \`server.js:3613\`**
   - **Trigger**: User purges vendor lots for a raw material.
   - **Fields Changed**: Filters out or zeros remaining stock for batches matching the targeted vendor.
   - **Atomicity**: Atomic via \`writeJSONAtomic\`.

10. **Direct Batch Inward: \`POST /api/raw-materials/:id/batches\` at \`server.js:3807\`**
    - **Trigger**: Direct REST API call to add a batch.
    - **Fields Changed**: Pushes new batch object with parsed quantities.
    - **Atomicity**: Atomic via \`writeJSONAtomic\`.

11. **Manufacturing Batch Commit: \`POST /api/manufacturing-batches/commit\` at \`server.js:4654\`**
    - **Trigger**: User commits formula production.
    - **Fields Changed & Transformation Logic**:
      Allocates consumed ingredients across active child batches using FIFO or vendor preference, decrements \`remainingQuantity\`, sets \`status = 'CONSUMED'\` on 0.
    - **Atomicity**: Atomic via \`writeJSONAtomic\`. Not lock-protected.

### Where it's read
- \`reconcileRawMaterialBatches()\` (\`server.js:264\`): Evaluates active batch sum vs parent stock.
- \`generateRMBatchId()\` (\`server.js:247\`): Calculates maximum sequence number to generate next ID.
- \`DELETE /api/products/:productId/variants/:variantId\` (\`server.js:1007\`, \`1031\`, \`1067\`): Verifies batches exist and restores packaging stock.
- \`POST /api/products/:id/fill-bottles\` (\`server.js:1347\`): Retrieves active batches for packaging deduction.
- \`GET /api/raw-material-batches\` (\`server.js:3479\`): Returns full batch collection.
- \`GET /api/raw-materials/:id/batches\` (\`server.js:3485\`): Returns batches for a specific material.
- \`GET /api/raw-materials/:id/vendors\` (\`server.js:3522\`): Extracts unique vendors from batch history.
- \`POST /api/raw-materials/:id/delete-vendor\` (\`server.js:3580\`): Finds vendor batches to purge.
- \`GET /api/raw-material-batches/:id\` (\`server.js:3669\`): Fetches single batch record.
- \`GET /api/raw-material-batches/:id/traceability\` (\`server.js:3682\`): Computes downstream lineage (which manufacturing batches and invoices used this lot).
- \`POST /api/manufacturing-batches/preview\` (\`server.js:4125\`): Evaluates FIFO / vendor lot availability.
- \`POST /api/manufacturing-batches/commit\` (\`server.js:4253\`): Performs batch allocation and consumption.

### Full lifecycle
- **CREATE**: Created upon inward purchase (\`POST /api/raw-materials/:id/add-stock\`), opening stock on material creation (\`POST /api/raw-materials\`), or startup reconciliation baseline.
- **UPDATE**:
  - \`remainingQuantity\` decremented upon packaging runs (\`fill-bottles\`) or manufacturing commits (\`commit\`).
  - \`remainingQuantity\` incremented and status restored to \`'ACTIVE'\` upon variant deletion (\`REVERSE\`).
  - \`unit\` and \`rawMaterialName\` updated if parent raw material is modified via \`PUT /api/raw-materials/:id\`.
- **DELETE**: Hard delete. Batches are spliced/filtered out when:
  - Parent raw material is deleted (\`DELETE /api/raw-materials/:id\`).
  - Vendor is purged (\`POST /api/raw-materials/:id/delete-vendor\`).
- **Audit Logging**: Inward purchases log \`INVENTORY_IN\` to \`manufacturing_audit.json\`. Consumptions log \`INVENTORY_OUT\` or \`FORMULATION_DEDUCTION\`. Reversals log \`TRANSACTION_REVERSAL\`.

### Cross-file transactions
Participates in inward purchases, manufacturing commits, bottling runs, and variant reversals. In all cases except \`fill-bottles\`, multiple JSON files are written sequentially without a unified transaction or lock.

### Known edge cases / validation gaps
- **No Transaction Rollback**: If a manufacturing commit exhausts stock on ingredient 3 of 5, earlier ingredients may have already been partially allocated in memory; the commit fails with 400 before writing, which protects disk, but if a crash occurs *during* the 8 sequential file writes, data drift occurs.
- **Stale Batch Reversal Block**: In variant deletion reversal (\`server.js:1031\`), if any original batch was deleted or purged, the entire reversal fails with HTTP 400 (\`Original Raw Material batch ... no longer exists\`), blocking automatic unwinding.

---

## raw_material_transactions.json

### Schema
- Top-level Container: Object with keys:
  - \`raw_material_transactions\`: Array of Transaction records (Required)
  - \`lastUpdated\`: String ISO 8601 timestamp (Required)
- Record Fields:
  - \`id\`: String (Required). Primary Key. Format: \`RMT-XXXXXX\` via \`uid('RMT')\`.
  - \`transactionId\`: String (Required alias). Format: \`TXN-XXXXXX\` via \`uid('TXN')\`.
  - \`auditCorrelationId\`: String (Required). Shared correlation ID: \`AUD-YYYY-NNNNNN\`.
  - \`operationType\`: String (Required). Operation enum:
    - \`'PURCHASE_INWARD'\`
    - \`'VARIANT_PACKAGING'\`
    - \`'TRANSACTION_REVERSAL'\`
    - \`'MANUFACTURING_CONSUMPTION'\`
    - \`'RECORD_DELETION'\`
  - \`transactionType\`: String (Required alias). Values: \`'PURCHASE_RECEIPT'\`, \`'PACKAGING_DEDUCTION'\`, \`'REVERSAL_INWARD'\`, \`'FORMULATION_DEDUCTION'\`.
  - \`action\`: String (Required). Descriptive action label (e.g. \`'Packaging Deduction'\`, \`'Inward Receipt'\`).
  - \`type\`: String (Required). Inventory direction: \`'IN'\` or \`'OUT'\`.
  - \`rawMaterialId\`: String (Required). References \`raw_materials.json\`.
  - \`rawMaterialName\`: String (Optional). Denormalized material name.
  - \`productId\`: String (Optional). References \`products.json\`.
  - \`productName\`: String (Optional).
  - \`variantId\`: String (Optional). References variant in \`products.json\`.
  - \`variantName\`: String (Optional).
  - \`manufacturingBatchId\`: String (Optional). References \`manufacturing_batches.json\`.
  - \`quantity\`: Number (Required). Float. Quantity moved.
  - \`quantityProduced\`: Number (Optional). Packaged finished units produced.
  - \`quantityReversed\`: Number (Optional, default \`0\`). Units reversed back to RM.
  - \`remainingReversibleQuantity\`: Number (Optional). Units eligible for future reversal.
  - \`reversed\`: Boolean (Optional, default \`false\`). True if completely reversed.
  - \`reversalOfTransactionId\`: String (Optional). References the original deduction transaction ID being reversed.
  - \`unit\`: String (Required). Unit of measurement.
  - \`allocations\`: Array of Objects (Optional). Breakdown of lot consumption:
    \`\`\`json
    [
      {
        "batchId": "RMB-2026-0001",
        "supplierBatchNumber": "LOT-992",
        "vendorId": "VEND-1",
        "vendorName": "Apex Packaging",
        "quantity": 50,
        "quantityReversed": 0,
        "unitCost": 12.5,
        "totalCost": 625
      }
    ]
    \`\`\`
  - \`totalCost\`: Number (Optional). Total monetary valuation.
  - \`operatorName\`: String (Optional).
  - \`reason\`: String (Optional). Reason for action.
  - \`notes\`: String (Optional).
  - \`date\`: String (Required). \`YYYY-MM-DD\`.
  - \`time\`: String (Required). \`HH:MM:SS\`.
  - \`timestamp\`: String (Required). ISO 8601 timestamp.
  - \`createdAt\`: String (Optional alias).
- Foreign Keys / References:
  - References \`raw_materials.json\` (\`rawMaterialId\`).
  - References \`raw_material_batches.json\` (\`allocations[].batchId\`).
  - References \`products.json\` (\`productId\`, \`variantId\`).
  - References \`manufacturing_batches.json\` (\`manufacturingBatchId\`).

### Where it's written
1. **Startup Normalizer: \`normalizeHistoricalAuditData()\` at \`server.js:425\`**
   - Assigns missing \`auditCorrelationId\` (\`AUD-YYYY-NNNNNN\`) to legacy transaction entries.
   - **Atomicity**: Atomic via \`writeJSONAtomic\`.
2. **Variant Deletion (Reversal): \`DELETE /api/products/:productId/variants/:variantId\` at \`server.js:1185\`**
   - Marks original deduction transaction: \`quantityReversed += reverseUnitsThisTxn\`, \`remainingReversibleQuantity -= reverseUnitsThisTxn\`, \`reversed = true\` if 0.
   - Pushes new reversal transaction (\`type: 'IN'\`, \`action: 'Transaction Reversal'\`, \`reversalOfTransactionId\`).
   - **Atomicity**: Atomic via \`writeJSONAtomic\`.
3. **Bottling Run Packaging Deduction: \`POST /api/products/:id/fill-bottles\` at \`server.js:1506\`**
   - Pushes \`VARIANT_PACKAGING\` deduction transaction with full allocation records.
   - **Atomicity**: Protected by \`withInventoryLock\`. Written via \`writeJSONAtomic\`.
4. **Audit Ledgers Purge: \`DELETE /api/audit-ledgers\` at \`server.js:2270\`**
   - Empties transactions to \`{ raw_material_transactions: [], lastUpdated: now }\`.
   - **Atomicity**: Atomic via \`writeJSONAtomic\`.
5. **System Data Reset: \`POST /api/system/reset-data\` at \`server.js:2346\`**
   - Empties collection on factory wipe.
   - **Atomicity**: Atomic via \`writeJSONAtomic\`.
6. **Legacy Data Import: \`POST /api/import-data\` at \`server.js:2515\`**
   - Overwrites transactions array.
   - **Atomicity**: Non-atomic via \`writeJSON\` (\`fs.writeFileSync\`).
7. **Opening Stock Transaction: \`POST /api/raw-materials\` at \`server.js:3093\`**
   - Pushes \`PURCHASE_RECEIPT\` transaction if opening stock > 0.
   - **Atomicity**: Atomic via \`writeJSONAtomic\`.
8. **Inward Purchase: \`POST /api/raw-materials/:id/add-stock\` at \`server.js:3448\`**
   - Pushes \`PURCHASE_INWARD\` transaction with vendor lot details.
   - **Atomicity**: Atomic via \`writeJSONAtomic\`.
9. **Manufacturing Commit: \`POST /api/manufacturing-batches/commit\` at \`server.js:4653\`**
   - Pushes \`MANUFACTURING_CONSUMPTION\` transaction recording all consumed ingredient lots.
   - **Atomicity**: Atomic via \`writeJSONAtomic\`.

### Where it's read
- \`generateAuditCorrelationId()\` (\`server.js:222\`): Scans for max \`AUD-YYYY-NNNNNN\` sequence.
- \`normalizeHistoricalAuditData()\` (\`server.js:401\`): Startup normalization.
- \`GET .../variants/:variantId/deletion-impact\` (\`server.js:916\`): Reads non-reversed packaging transactions to compute \`maxEligibleReversal\`.
- \`DELETE .../variants/:variantId\` (\`server.js:1006\`): Reads packaging transactions to unwind allocations.
- \`GET /api/raw-materials/:id/history\` (\`server.js:3504\`): Returns transaction ledger for a raw material.
- \`GET /api/raw-material-batches/:id/traceability\` (\`server.js:3684\`): Matches allocations to trace batch usage.
- \`GET /api/raw-material-transactions\` (\`server.js:3813\`): Serves full transaction history to UI.

### Full lifecycle
- **CREATE**: Created upon inward purchases, production deductions, and variant reversals. Never deleted individually.
- **UPDATE**: Only packaging transactions are mutated: \`quantityReversed\`, \`remainingReversibleQuantity\`, and \`reversed\` flags are updated during variant deletion reversal.
- **DELETE**: Append-only store. Wiped completely on \`DELETE /api/audit-ledgers\` or factory reset.
- **Audit Logging**: Correlated with \`manufacturing_audit.json\` via \`auditCorrelationId\`.

### Cross-file transactions
Always written in conjunction with \`raw_materials.json\`, \`raw_material_batches.json\`, and \`manufacturing_audit.json\`.

### Known edge cases / validation gaps
- **Contradiction with Documentation**: Deleting a Raw Material does not remove its entries from \`raw_material_transactions.json\`, leaving orphan \`rawMaterialId\` values.
- **Audit Clear Guarantees**: Clearing audit ledgers (\`DELETE /api/audit-ledgers\`) wipes \`raw_material_transactions.json\`. Subsequent variant deletions can no longer reverse packaging to original batches because the allocation records are gone.

---
`);
};
