const fs = require('fs');

module.exports = function(append) {
  append(`## raw_materials.json

### Schema
- Top-level Container: Object with keys:
  - \`raw_materials\`: Array of Raw Material records (Required)
  - \`lastUpdated\`: String ISO 8601 timestamp (Required)
- Record Fields:
  - \`id\`: String (Required). Primary Key. Format: \`RM-XXXXXX\` where suffix is timestamp + alphanumeric random. Generated by:
    \`\`\`javascript
    // server.js:205
    const uid = (prefix) => \`\${prefix}-\${Date.now()}-\${Math.random().toString(36).substr(2,6).toUpperCase()}\`;
    // Called as: uid('RM')
    \`\`\`
  - \`name\`: String (Required). Trimmed material name. Validated at \`server.js:2972\`: \`if (!name || !name.trim()) return res.status(400).json({ error: 'Raw material name is required' });\`. Unique across store (case-insensitive check at \`server.js:2975\`).
  - \`unit\`: String (Required). Unit of measurement (e.g., \`kg\`, \`g\`, \`L\`, \`mL\`, \`pcs\`, \`box\`, \`carton\`). Validated at \`server.js:2973\`: \`if (!unit || !unit.trim()) return res.status(400).json({ error: 'Unit type is required' });\`.
  - \`current_stock\`: Number (Required). Float representing total active stock. Must equal the sum of active child batches in \`raw_material_batches.json\`.
  - \`stock\`: Number (Optional / Legacy alias). Mirrored to \`current_stock\`.
  - \`quantity\`: Number (Optional / Legacy alias). Set to initial stock upon creation (\`server.js:3005\`).
  - \`openingStock\`: Number (Optional). Initial stock quantity supplied at record creation (\`server.js:2999\`).
  - \`minStock\`: Number (Optional, default \`0\`). Minimum reorder threshold. Parsed via \`parseFloat(req.body.minStock !== undefined ? req.body.minStock : req.body.reorder_level) || 0\` (\`server.js:2966\`).
  - \`reorder_level\`: Number (Optional alias). Stored to match \`minStock\` (\`server.js:3002\`).
  - \`cost_per_unit\`: Number (Optional, default \`0\`). Cost per unit in INR. Parsed via \`parseFloat(req.body.cost_per_unit !== undefined ? req.body.cost_per_unit : req.body.price) || 0\` (\`server.js:2964\`).
  - \`price\`: Number (Optional alias). Stored to match \`cost_per_unit\` (\`server.js:3003\`).
  - \`category\`: String (Optional, default \`'Raw Material'\`). Normalized string (e.g., \`'Packaging'\`, \`'Raw Material'\`, \`'Ingredient'\`).
  - \`supplier\`: String (Optional). Default vendor name (\`server.js:2995\`).
  - \`vendorName\`: String (Optional alias). Synced to \`supplier\` (\`server.js:2996\`).
  - \`hsn\`: String (Optional). HSN/SAC code (\`server.js:2997\`).
  - \`notes\`: String (Optional). Text notes (\`server.js:2998\`).
  - \`createdAt\`: String (Required). ISO 8601 timestamp (\`server.js:3006\`).
  - \`updatedAt\`: String (Required). ISO 8601 timestamp (\`server.js:3007\`).
- Foreign Keys / References:
  - Inward reference from \`raw_material_batches.json\` (\`rawMaterialId\`): Enforced at batch creation (\`server.js:3315\`). Validated on startup by \`reconcileRawMaterialBatches()\` (\`server.js:274\`).
  - Inward reference from \`recipes.json\` (\`ingredients[].rawMaterialId\`): Validated at recipe creation/update (\`server.js:3843\`, \`server.js:3905\`). Checked as a blocking dependency before RM deletion at \`server.js:3172\`.
  - Inward reference from \`products.json\` (\`variants[].packagingRawMaterialId\`): Validated during bottling (\`server.js:1335\`). Checked as a blocking dependency before RM deletion at \`server.js:3189\`.
  - Inward reference from \`raw_material_transactions.json\` (\`rawMaterialId\`): Logged on transaction creation (\`server.js:1506\`, \`3093\`, \`3448\`, \`4653\`).

### Where it's written
1. **Startup Reconciliation: \`reconcileRawMaterialBatches()\` at \`server.js:371\`**
   - **Trigger**: Server launch execution (line 478).
   - **Fields Changed & Transformation Logic**:
     \`\`\`javascript
     // server.js:353-363
     const finalBatchesSum = rmbData.raw_material_batches
       .filter(b => b.rawMaterialId === rm.id && (b.status === 'ACTIVE' || (b.remainingQuantity > 0 && b.status !== 'CONSUMED')))
       .reduce((sum, b) => sum + (b.remainingQuantity || 0), 0);

     const reconciledStock = parseFloat(finalBatchesSum.toFixed(6));
     if (rm.current_stock !== reconciledStock || rm.stock !== reconciledStock) {
       rm.current_stock = reconciledStock;
       rm.stock = reconciledStock;
       rmChanged = true;
     }
     \`\`\`
   - **Atomicity**: Atomic file replacement via \`writeJSONAtomic(RAW_MATERIALS_FILE, rmData)\` (tmp file + \`fs.renameSync\`). No in-memory mutex lock.

2. **Variant Deletion (Reversal): \`DELETE /api/products/:productId/variants/:variantId\` at \`server.js:1181\`**
   - **Trigger**: User deletes a product variant with \`action: 'REVERSE'\`.
   - **Fields Changed & Transformation Logic**:
     \`\`\`javascript
     // server.js:1169-1172
     const curRmStock = rm.current_stock !== undefined ? rm.current_stock : (rm.stock || 0);
     rm.current_stock = parseFloat((curRmStock + totalPackagingRestored).toFixed(6));
     rm.stock = rm.current_stock;
     rm.updatedAt = timestamp;
     \`\`\`
   - **Atomicity**: Atomic file replacement via \`writeJSONAtomic\`. Not wrapped in \`withInventoryLock\`.

3. **Packaging / Bottling Run: \`POST /api/products/:id/fill-bottles\` at \`server.js:1468\`**
   - **Trigger**: User submits bottling/packaging modal.
   - **Fields Changed & Transformation Logic**:
     \`\`\`javascript
     // server.js:1330-1467
     const packagingNeeded = numBottles * (variant.packagingQty || 1);
     const curRmStock = rm.current_stock !== undefined ? rm.current_stock : (rm.stock || 0);
     rm.current_stock = Math.max(0, parseFloat((curRmStock - packagingNeeded).toFixed(6)));
     rm.stock = rm.current_stock;
     rm.updatedAt = timestamp;
     \`\`\`
   - **Atomicity**: Wrapped in \`withInventoryLock\` (in-memory Promise queue + atomic \`.inventory.lock\` file lock via \`fs.openSync(..., 'wx')\`). Written via \`writeJSONAtomic\`.

4. **System Data Reset: \`POST /api/system/reset-data\` at \`server.js:2340\`**
   - **Trigger**: User executes factory data wipe in Settings.
   - **Fields Changed**: Cleared to empty array \`{ raw_materials: [], lastUpdated: new Date().toISOString() }\`.
   - **Atomicity**: Atomic via \`writeJSONAtomic\`. Not lock-protected.

5. **Legacy Data Import: \`POST /api/import-data\` at \`server.js:2499\`**
   - **Trigger**: User imports full JSON backup file via legacy endpoint.
   - **Fields Changed**: Overwritten with \`{ raw_materials: rawMaterialsList, lastUpdated: new Date().toISOString() }\`.
   - **Atomicity**: **NON-ATOMIC**. Quoted from code:
     \`\`\`javascript
     // server.js:2499
     writeJSON(RAW_MATERIALS_FILE, { raw_materials: rawMaterialsList, lastUpdated: new Date().toISOString() });
     \`\`\`
     Calls \`writeJSON\` which performs direct \`fs.writeFileSync\`. Can leave corrupted partial file if interrupted.

6. **Modular Data Import: \`POST /api/import-data/:section\` at \`server.js:2694\`**
   - **Trigger**: User imports specific JSON section (\`section === 'raw-materials'\` or \`'all'\`).
   - **Fields Changed**: Slices/merges raw materials list into store.
   - **Atomicity**: Atomic via \`writeJSONAtomic\`.

7. **Create Raw Material: \`POST /api/raw-materials\` at \`server.js:3008\`**
   - **Trigger**: User submits "+ Add Raw Material" form.
   - **Fields Changed & Transformation Logic**:
     Pushes new record with generated ID \`uid('RM')\`, sets \`current_stock = initialStock\`, \`stock = initialStock\`, \`cost_per_unit\`, \`category\`, \`createdAt\`.
   - **Atomicity**: **NON-ATOMIC**. Quoted from code:
     \`\`\`javascript
     // server.js:3008
     writeJSON(RAW_MATERIALS_FILE, d);
     \`\`\`
     Calls \`writeJSON\` (direct \`fs.writeFileSync\`), NOT \`writeJSONAtomic\`.

8. **Update Raw Material: \`PUT /api/raw-materials/:id\` at \`server.js:3138\`**
   - **Trigger**: User edits raw material fields.
   - **Fields Changed & Transformation Logic**:
     Updates \`name\`, \`category\`, \`minStock\`, \`cost_per_unit\`, \`supplier\`, \`hsn\`, \`notes\`. If \`unit\` changed:
     \`\`\`javascript
     // server.js:3125-3126
     item.unit = unit.trim();
     unitChanged = true;
     \`\`\`
   - **Atomicity**: **NON-ATOMIC**. Quoted from code:
     \`\`\`javascript
     // server.js:3138
     writeJSON(RAW_MATERIALS_FILE, d);
     \`\`\`
     Calls \`writeJSON\` (direct \`fs.writeFileSync\`), NOT \`writeJSONAtomic\`.

9. **Delete Raw Material: \`DELETE /api/raw-materials/:id\` at \`server.js:3286\`**
   - **Trigger**: User clicks Delete on a raw material.
   - **Fields Changed**: Spliced from \`raw_materials\` array (\`d.raw_materials.splice(idx, 1)\`).
   - **Atomicity**: Atomic via \`writeJSONAtomic\`.

10. **Add Stock / Inward Purchase: \`POST /api/raw-materials/:id/add-stock\` at \`server.js:3446\`**
    - **Trigger**: User submits "+ Add Stock" inward purchase batch form.
    - **Fields Changed & Transformation Logic**:
      \`\`\`javascript
      // server.js:3441-3443
      const curStock = rm.current_stock !== undefined ? rm.current_stock : (rm.stock || 0);
      rm.current_stock = parseFloat((curStock + qty).toFixed(6));
      rm.stock = rm.current_stock;
      rm.updatedAt = new Date().toISOString();
      \`\`\`
    - **Atomicity**: Atomic via \`writeJSONAtomic\`. Not lock-protected.

11. **Delete Vendor Lot: \`POST /api/raw-materials/:id/delete-vendor\` at \`server.js:3642\`**
    - **Trigger**: User deletes a specific vendor and purges all their batches for this material.
    - **Fields Changed & Transformation Logic**:
      \`\`\`javascript
      // server.js:3638-3640
      const currentParent = rm.current_stock !== undefined ? rm.current_stock : (rm.stock || 0);
      rm.current_stock = Math.max(0, parseFloat((currentParent - totalDeductedQty).toFixed(6)));
      rm.stock = rm.current_stock;
      \`\`\`
    - **Atomicity**: Atomic via \`writeJSONAtomic\`.

12. **Manufacturing Batch Commit: \`POST /api/manufacturing-batches/commit\` at \`server.js:4652\`**
    - **Trigger**: User commits a manufactured formula batch run.
    - **Fields Changed & Transformation Logic**:
      Iterates over allocated recipe ingredients and deducts consumed amounts:
      \`\`\`javascript
      // server.js:4584-4589
      const curStock = rm.current_stock !== undefined ? rm.current_stock : (rm.stock || 0);
      rm.current_stock = Math.max(0, parseFloat((curStock - totalConsumedThisIng).toFixed(6)));
      rm.stock = rm.current_stock;
      rm.updatedAt = new Date().toISOString();
      \`\`\`
    - **Atomicity**: Atomic via \`writeJSONAtomic\`. **Not protected by \`withInventoryLock\`**.

### Where it's read
- \`reconcileRawMaterialBatches()\` (\`server.js:263\`): Calculates stock invariants on server startup.
- \`GET /api/products/:productId/variants/:variantId/deletion-impact\` (\`server.js:939\`): Reads current stock and unit of packaging material for impact preview.
- \`DELETE /api/products/:productId/variants/:variantId\` (\`server.js:1008\`): Looks up packaging material to restore stock upon variant reversal.
- \`POST /api/products/:id/fill-bottles\` (\`server.js:1335\`): Checks packaging RM existence and stock sufficiency.
- \`GET /api/export-data\` (\`server.js:2374\`): Exports full collection to backup bundle.
- \`POST /api/import-data\` (\`server.js:2474\`): Takes pre-import snapshot.
- \`POST /api/import-data/:section\` (\`server.js:2595\`, \`2673\`): Pre-import backup and section import read.
- \`GET /api/raw-materials\` (\`server.js:2956\`): Serves material list to UI.
- \`GET /api/raw-materials/:id\` (\`server.js:2962\`): Returns single material record.
- \`POST /api/raw-materials\` (\`server.js:2970\`): Checks for duplicate names.
- \`PUT /api/raw-materials/:id\` (\`server.js:3103\`): Retrieves record to update.
- \`DELETE /api/raw-materials/:id\` (\`server.js:3165\`): Validates RM exists and checks blocking dependencies.
- \`POST /api/raw-materials/:id/add-stock\` (\`server.js:3313\`): Validates RM exists before recording batch.
- \`GET /api/raw-materials/:id/batches\` (\`server.js:3484\`): Validates parent RM exists.
- \`GET /api/raw-materials/:id/vendors\` (\`server.js:3513\`): Loads material to extract vendor lots.
- \`POST /api/raw-materials/:id/delete-vendor\` (\`server.js:3577\`): Validates material exists before vendor purge.
- \`POST /api/raw-materials/:id/batches\` (\`server.js:3773\`): Validates material exists.
- \`POST /api/recipes\` (\`server.js:3843\`) & \`PUT /api/recipes/:id\` (\`server.js:3905\`): Validates ingredient RM exists and unit matches recipe line.
- \`POST /api/manufacturing-batches/preview\` (\`server.js:4124\`): Reads current stock to evaluate FIFO and vendor allocation feasibility.
- \`POST /api/manufacturing-batches/commit\` (\`server.js:4252\`): Reads stock for allocation and deduction.
- \`GET /api/context\` (\`server.js:5375\`): Extracts raw material summary for prompt context.
- \`GET /api/stats\` (\`server.js:5418\`): Computes total raw material count and total inventory valuation.
- \`POST /api/ai/invoke\` (\`server.js:5477\`): Feeds raw material context into AI assistant.

### Full lifecycle
- **CREATE**:
  - **Trigger**: \`POST /api/raw-materials\`.
  - **Files written in same operation**:
    1. \`raw_materials.json\` (\`server.js:3008\`)
    2. \`raw_material_batches.json\` (\`server.js:3052\`, if initial stock > 0, creates baseline opening batch)
    3. \`raw_material_transactions.json\` (\`server.js:3093\`, if initial stock > 0, creates \`PURCHASE_RECEIPT\` transaction)
    4. \`manufacturing_audit.json\` (\`server.js:3205\`, logs \`INVENTORY_IN\` audit event)
  - **Failure behavior**: Non-atomic multi-file write without rollback. If writing \`raw_material_batches.json\` fails, \`raw_materials.json\` retains the record with initial stock but child batch is missing, causing \`reconcileRawMaterialBatches()\` to attempt self-healing on next launch.
- **UPDATE**:
  - \`PUT /api/raw-materials/:id\`: Mutates metadata (\`name\`, \`unit\`, \`minStock\`, \`cost_per_unit\`, \`supplier\`, \`hsn\`, \`notes\`). Cascades \`unit\` and \`name\` changes to all associated child batches in \`raw_material_batches.json\` (\`server.js:3155\`).
  - Stock mutations occur via:
    - \`POST /api/raw-materials/:id/add-stock\`: Increases \`current_stock\`.
    - \`POST /api/products/:id/fill-bottles\`: Decreases \`current_stock\` by \`packagingNeeded\`.
    - \`POST /api/manufacturing-batches/commit\`: Decreases \`current_stock\` by consumed ingredient amount.
    - \`DELETE /api/products/:id/variants/:variantId\` (\`REVERSE\`): Increases \`current_stock\` by restored packaging.
    - \`POST /api/raw-materials/:id/delete-vendor\`: Decreases \`current_stock\` by purged vendor stock.
- **DELETE**:
  - **Mechanism**: Hard delete via \`d.raw_materials.splice(idx, 1)\` (\`server.js:3286\`).
  - **Pre-condition Checks**: Blocked with HTTP 400 if referenced in:
    1. Active manufacturing batches (\`server.js:3170\`)
    2. Recipe ingredients in \`recipes.json\` (\`server.js:3172\`)
    3. Product variants as \`packagingRawMaterialId\` in \`products.json\` (\`server.js:3189\`)
  - **Cascading Effects**:
    - \`raw_material_batches.json\`: Slices out all child batches matching \`rawMaterialId\` (\`server.js:3293\`).
    - \`manufacturing_audit.json\`: Logs \`DATA_DELETION\` audit entry with correlation ID (\`server.js:3278\`).
    - \`raw_material_transactions.json\`: **NO CASCADING CLEANUP**. Historical transactions retain the deleted \`rawMaterialId\`, leaving orphan foreign keys.
  - **Reversal/Undo**: None. Hard delete is permanent.
- **Audit Logging**:
  - Creation with stock logs \`INVENTORY_IN\` to \`manufacturing_audit.json\` with correlation ID \`AUD-YYYY-NNNNNN\` (\`server.js:3205\`).
  - Updates log \`INVENTORY_ADJUSTMENT\` to \`manufacturing_audit.json\` (\`server.js:3242\`).
  - Deletion logs \`DATA_DELETION\` (\`entityType: 'RAW_MATERIAL'\`) to \`manufacturing_audit.json\` (\`server.js:3278\`).

### Cross-file transactions
- **Bottling Run**: \`products.json\` (\`server.js:1456\`) $\\rightarrow$ \`raw_materials.json\` (\`server.js:1468\`) $\\rightarrow$ \`raw_material_batches.json\` (\`server.js:1469\`) $\\rightarrow$ \`raw_material_transactions.json\` (\`server.js:1506\`) $\\rightarrow$ \`manufacturing_audit.json\` (\`server.js:1533\`) $\\rightarrow$ \`finished_goods.json\` (\`server.js:1559\`) $\\rightarrow$ \`finished_goods_transactions.json\` (\`server.js:1560\`).
  - **Locking**: Wrapped in \`withInventoryLock\`.
  - **Failure Risk**: Individual file writes are sequential \`writeJSONAtomic\` calls. If node process crashes after writing \`raw_materials.json\`, packaging RM stock is deducted while finished goods pool was not deducted.
- **Manufacturing Commit**: \`products.json\` (\`server.js:4641\`) $\\rightarrow$ \`raw_materials.json\` (\`server.js:4652\`) $\\rightarrow$ \`raw_material_transactions.json\` (\`server.js:4653\`) $\\rightarrow$ \`raw_material_batches.json\` (\`server.js:4654\`) $\\rightarrow$ \`finished_goods.json\` (\`server.js:4655\`) $\\rightarrow$ \`finished_goods_transactions.json\` (\`server.js:4656\`) $\\rightarrow$ \`manufacturing_batches.json\` (\`server.js:4657\`) $\\rightarrow$ \`manufacturing_audit.json\` (\`server.js:4658\`).
  - **Locking**: **NONE**. No mutex lock or transactional wrapper.
  - **Failure Risk**: High if interrupted mid-loop. 8 separate file writes.

### Known edge cases / validation gaps
- **Contradiction with Documentation**: Documentation claims all JSON writes are atomic. In reality, \`POST /api/raw-materials\` (\`server.js:3008\`), \`PUT /api/raw-materials/:id\` (\`server.js:3138\`), and \`POST /api/import-data\` (\`server.js:2499\`) call \`writeJSON\` which performs synchronous non-atomic \`fs.writeFileSync\`.
- **Concurrency Gap**: \`POST /api/raw-materials/:id/add-stock\` is not wrapped in \`withInventoryLock\`. Rapid concurrent inward calls can experience lost updates during read-modify-write cycles.
- **Orphan Transactions**: Deleting a raw material deletes the master and child batches but leaves historical records in \`raw_material_transactions.json\` pointing to a non-existent \`rawMaterialId\`.
- **Negative Stock Vulnerability**: \`rm.current_stock\` can theoretically be driven negative if external edits corrupt \`raw_material_batches.json\`, though runtime math enforces \`Math.max(0, ...)\` on bottling and batch commit.

---
`);
};
