const fs = require('fs');

module.exports = function(append) {
  append(`## products.json

### Schema
- Top-level Container: Object with keys:
  - \`products\`: Array of Product records (Required)
  - \`lastUpdated\`: String ISO 8601 timestamp (Required)
- Record Fields:
  - \`id\`: String (Required). Primary Key. Format: \`PRD-XXXXXX\`. Generated by:
    \`\`\`javascript
    // server.js:205
    const uid = (prefix) => \`\${prefix}-\${Date.now()}-\${Math.random().toString(36).substr(2,6).toUpperCase()}\`;
    // Called as: uid('PRD')
    \`\`\`
  - \`name\`: String (Required). Validated non-empty at \`server.js:680\`: \`if (!name || !name.trim()) return res.status(400).json({ error: 'Product name is required' });\`.
  - \`hsn_sac\`: String (Optional, default \`'3004'\`). GST HSN/SAC code.
  - \`rate\`: Number (Optional, default \`0\`). Base selling price.
  - \`category\`: String (Optional). Classification tag.
  - \`description\`: String (Optional).
  - \`recipeId\`: String (Optional). Foreign Key referencing \`recipes.json\`. Back-linked during formulation or startup reconciliation.
  - \`bulkStock\`: Number (Optional, default \`0\`). Float. Manufactured bulk quantity available for packaging. Synchronized from \`finished_goods.json\`.
  - \`bulkStockUnit\`: String (Optional, default \`'kg'\`). Measurement unit of bulk stock (\`'kg'\`, \`'g'\`, \`'L'\`, \`'mL'\`).
  - \`stock\`: Number (Optional, default \`0\`). Legacy unvarianted stock counter.
  - \`variants\`: Array of Product Variation records (Required array, may be empty \`[]\` upon catalog creation, but invoices strictly require at least one variant).
    - Variant Record Fields:
      - \`variantId\`: String (Required). Format: \`VAR-XXXXXX\` via \`uid('VAR')\` or user/test assigned string (e.g., \`VAR-1\`).
      - \`name\`: String (Required). Label (e.g. *Sugar Water Drink - 500 mL*, *Herbal Balm - 1 Box*).
      - \`bottleSize\`: Number (Required). Numeric capacity (Float > 0).
      - \`bottleSizeUnit\`: String (Required). Container unit. Supports mass (\`g\`, \`kg\`, \`mg\`), volume (\`mL\`, \`L\`), discrete counts (\`box\`, \`carton\`, \`bottle\`, \`container\`, \`jar\`, \`pouch\`, \`tube\`, \`vial\`, \`pcs\`).
      - \`packagingRawMaterialId\`: String (Optional / Recommended). Foreign Key referencing container item in \`raw_materials.json\`. Single source of truth for packaging materials.
      - \`packagingQty\`: Number (Optional, default \`1\`). Packaging units deducted per finished container.
      - \`vendorPreference\`: Object (Optional):
        - \`mode\`: String (\`'FIFO'\` | \`'VENDOR'\`).
        - \`vendorId\`: String | null.
        - \`vendorName\`: String | null.
      - \`price\`: Number (Required). Selling price per finished pack in INR.
      - \`stock\`: Number (Required, default \`0\`). Current ready-to-sell packaged finished goods inventory.
  - \`createdAt\`: String (Required). ISO 8601 timestamp.
  - \`updatedAt\`: String (Required). ISO 8601 timestamp.
- Foreign Keys / References:
  - References \`recipes.json\` (\`recipeId\`): Synced on startup by \`reconcileFinishedGoodsAndProducts()\` (\`server.js:558\`). Cleared if recipe deleted (\`server.js:4001\`).
  - References \`raw_materials.json\` (\`variants[].packagingRawMaterialId\`): Validated during bottling deduction (\`server.js:1335\`). Blocks RM deletion if referenced (\`server.js:3189\`).
  - Inward reference from \`finished_goods.json\` (\`productId\`): Links bulk manufactured pool to product.
  - Inward reference from \`invoices.json\` (\`items[].productId\`, \`items[].variantId\`): Validated at invoice creation (\`server.js:1807-1835\`).

### Where it's written
1. **Startup Reconciliation: \`reconcileFinishedGoodsAndProducts()\` at \`server.js:602\`**
   - **Trigger**: Server launch execution (line 611).
   - **Fields Changed & Transformation Logic**:
     Converts finished goods stock to product \`bulkStock\` and reconciles \`recipeId\` back-links:
     \`\`\`javascript
     // server.js:569-588
     const fgStock  = fg.currentStock || 0;
     const fgSize   = fg.bottleSize   || 1;
     const fgUnit   = fg.bottleSizeUnit || 'kg';
     const bulkUnit = p.bulkStockUnit || fgUnit;
     let totalBulk;
     try {
       const totalInFGUnit = fgStock * fgSize;
       totalBulk = unitConv.convert(totalInFGUnit, fgUnit, bulkUnit);
     } catch (_) {
       totalBulk = fgStock * fgSize;
     }
     totalBulk = parseFloat(totalBulk.toFixed(6));
     p.bulkStock = totalBulk;
     p.bulkStockUnit = bulkUnit;
     \`\`\`
   - **Atomicity**: Atomic via \`writeJSONAtomic\`.

2. **Create Product: \`POST /api/products\` at \`server.js:711\`**
   - **Trigger**: User creates product in catalog.
   - **Fields Changed**: Generates \`id = uid('PRD')\`, normalizes \`variants\` array, saves to store.
   - **Atomicity**: Atomic via \`writeJSONAtomic\`.

3. **Update Product: \`PUT /api/products/:id\` at \`server.js:845\`**
   - **Trigger**: User edits product metadata or variant configuration.
   - **Fields Changed**: Updates name, rate, HSN, and replaces/merges variants.
   - **Atomicity**: Atomic via \`writeJSONAtomic\`.

4. **Delete Product: \`DELETE /api/products/:id\` at \`server.js:860\`**
   - **Trigger**: User deletes product.
   - **Fields Changed**: Spliced from \`products\` array (\`d.products.splice(idx, 1)\`).
   - **Atomicity**: Atomic via \`writeJSONAtomic\`.

5. **Delete Product Variant: \`DELETE /api/products/:productId/variants/:variantId\` at \`server.js:1213\`**
   - **Trigger**: User deletes specific variation with reason.
   - **Fields Changed**: \`product.variants.splice(vIdx, 1)\`.
   - **Atomicity**: Atomic via \`writeJSONAtomic\`.

6. **Bottling Run (Packaged Stock Increase): \`POST /api/products/:id/fill-bottles\` at \`server.js:1456\`**
   - **Trigger**: Bottling modal submitted.
   - **Fields Changed & Transformation Logic**:
     \`\`\`javascript
     // server.js:1453-1455
     variant.stock = Math.max(0, parseFloat(((variant.stock || 0) + numBottles).toFixed(4)));
     variant.updatedAt = timestamp;
     product.updatedAt = timestamp;
     \`\`\`
   - **Atomicity**: Wrapped in \`withInventoryLock\`. Atomic via \`writeJSONAtomic\`.

7. **Direct Variant Stock Adjustment: \`POST /api/products/:id/update-variant-stock\` at \`server.js:1718\`**
   - **Trigger**: Manual stock override.
   - **Fields Changed**: Sets \`variant.stock\` directly.
   - **Atomicity**: Atomic via \`writeJSONAtomic\`.

8. **Invoice Creation (Sales Stock Deduction): \`POST /api/invoices\` at \`server.js:1987\`**
   - **Trigger**: User issues sales invoice.
   - **Fields Changed & Transformation Logic**:
     Deducts sold quantity strictly from variant packaged stock:
     \`\`\`javascript
     // server.js:1984-1986
     v.stock = Math.max(0, (v.stock || 0) - item.qty);
     prd.updatedAt = new Date().toISOString();
     \`\`\`
   - **Atomicity**: Wrapped in \`withInventoryLock\`. Atomic via \`writeJSONAtomic\`.

9. **Invoice Cancellation (Restock): \`DELETE /api/invoices/:id?restock=true\` at \`server.js:2240\`**
   - **Trigger**: User cancels invoice with restock checked.
   - **Fields Changed & Transformation Logic**:
     Restores sold quantity to variant:
     \`\`\`javascript
     // server.js:2238-2239
     v.stock = (v.stock || 0) + item.qty;
     \`\`\`
   - **Atomicity**: Atomic via \`writeJSONAtomic\`. Not lock-protected.

10. **System Data Reset: \`POST /api/system/reset-data\` at \`server.js:2337\`**
    - **Trigger**: Factory reset.
    - **Fields Changed**: Cleared to \`{ products: [], lastUpdated: ... }\`.
    - **Atomicity**: Atomic via \`writeJSONAtomic\`.

11. **Legacy Import: \`POST /api/import-data\` at \`server.js:2490\`**
    - Overwritten with imported list.
    - **Atomicity**: Non-atomic via \`writeJSON\` (\`fs.writeFileSync\`).

12. **Modular Import: \`POST /api/import-data/:section\` at \`server.js:2781\`**
    - Merges product catalog.
    - **Atomicity**: Atomic via \`writeJSONAtomic\`.

13. **Recipe Deletion Cascade: \`DELETE /api/recipes/:id\` at \`server.js:4001\`**
    - Clears \`p.recipeId\` if matching deleted recipe.
    - **Atomicity**: Atomic via \`writeJSONAtomic\`.

14. **Manufacturing Commit: \`POST /api/manufacturing-batches/commit\` at \`server.js:4641\`**
    - Increases product's \`bulkStock\` by manufactured batch yield.
    - **Atomicity**: Atomic via \`writeJSONAtomic\`.

15. **Finished Good Deletion Cascade: \`DELETE /api/finished-goods/:id\` at \`server.js:5305\`**
    - Resets \`product.bulkStock = 0\` if linked finished good is deleted.
    - **Atomicity**: Atomic via \`writeJSONAtomic\`.

### Where it's read
- \`reconcileFinishedGoodsAndProducts()\` (\`server.js:488\`): Startup synchronization.
- \`GET /api/products\` (\`server.js:670\`): Serves product catalog.
- \`PUT /api/products/:id\` (\`server.js:747\`): Finds product to update.
- \`DELETE /api/products/:id\` (\`server.js:802\`): Validates product exists before deletion.
- \`GET /api/products/:id\` (\`server.js:895\`): Returns single product.
- \`GET .../deletion-impact\` (\`server.js:904\`): Reads variant stock and configuration.
- \`DELETE .../variants/:variantId\` (\`server.js:980\`): Finds variant to reverse/discard.
- \`POST /api/products/:id/fill-bottles\` (\`server.js:1257\`): Reads variant capacity and packaging RM.
- \`POST /api/invoices\` (\`server.js:1799\`): Validates product variants exist, checks available stock, and performs deduction.
- \`DELETE /api/invoices/:id\` (\`server.js:2202\`): Restores stock upon cancellation.
- \`DELETE /api/raw-materials/:id\` (\`server.js:3189\`): Dependency check blocking RM deletion if used by any variant.
- \`DELETE /api/recipes/:id\` (\`server.js:3994\`): Checks product back-links.
- \`POST /api/manufacturing-batches/commit\` (\`server.js:4634\`): Finds product linked to recipe.

### Full lifecycle
- **CREATE**: Created via \`POST /api/products\`. Variants can be added at creation or later.
- **UPDATE**: Updated via catalog edit, bottling run (+stock), invoice creation (-stock), invoice restock (+stock), or formula commit (+bulkStock).
- **DELETE**:
  - Entire Product: Hard delete (\`splice\`). Cascades: clears \`recipe.productId\` in \`recipes.json\` and \`fg.productId\` in \`finished_goods.json\`.
  - Single Variant: Hard delete (\`product.variants.splice\`). Preceded by optional packaging reversal or discard audit logging.
- **Audit Logging**: Catalog creation logs \`CATALOG_CREATE\` (\`server.js:739\`). Variant deletion logs \`DATA_DELETION\` (\`server.js:1241\`). Product deletion logs \`DATA_DELETION\` (\`server.js:833\`).

### Cross-file transactions
Participates in bottling runs (7 files), invoices (4 files), invoice cancellations (4 files), and manufacturing commits (8 files).

### Known edge cases / validation gaps
- **Strict Variant Requirement Contradiction**: Invoices require products to have variants (\`server.js:1807\`), but catalog product creation (\`POST /api/products\`) allows creating products with \`variants: []\`. Invoicing unconfigured products is blocked with HTTP 400 at runtime.
- **Negative Variant Stock Bypass**: Direct variant stock adjustment endpoint \`POST /api/products/:id/update-variant-stock\` does not enforce \`withInventoryLock\`.

---

## customers.json

### Schema
- Top-level Container: Object with keys:
  - \`customers\`: Array of Customer records (Required)
  - \`lastUpdated\`: String ISO 8601 timestamp (Required)
- Record Fields:
  - \`id\`: String (Required). Primary Key. Format: \`CUST-XXXXXX\` via \`uid('CUST')\`.
  - \`name\`: String (Required). Validated non-empty at \`server.js:1739\`.
  - \`email\`: String (Optional).
  - \`phone\`: String (Optional).
  - \`address\`: String (Optional).
  - \`city\`: String (Optional).
  - \`state\`: String (Optional). State name (used for GST tax split detection).
  - \`stateCode\`: String (Optional). 2-digit Indian GST state code (e.g. \`'27'\`, \`'07'\`).
  - \`pincode\`: String (Optional).
  - \`gstin\`: String (Optional). 15-character GSTIN.
  - \`pan\`: String (Optional). Permanent Account Number.
  - \`notes\`: String (Optional).
  - \`createdAt\`: String (Required). ISO 8601 timestamp.
  - \`updatedAt\`: String (Required). ISO 8601 timestamp.
- Foreign Keys / References:
  - Referenced by \`invoices.json\` (\`customer.id\` or denormalized customer snapshot).

### Where it's written
1. **Create Customer: \`POST /api/customers\` at \`server.js:1744\`**
   - **Trigger**: User saves new customer.
   - **Atomicity**: **NON-ATOMIC**. Quoted from code:
     \`\`\`javascript
     // server.js:1744
     writeJSON(CUSTOMERS_FILE, d);
     \`\`\`
     Calls \`writeJSON\` (\`fs.writeFileSync\`).
2. **Update Customer: \`PUT /api/customers/:id\` at \`server.js:1755\`**
   - **Trigger**: User edits customer profile.
   - **Atomicity**: **NON-ATOMIC**. Calls \`writeJSON\`.
3. **Delete Customer: \`DELETE /api/customers/:id\` at \`server.js:1770\`**
   - **Trigger**: User deletes customer.
   - **Atomicity**: Atomic via \`writeJSONAtomic\`.
4. **System Reset: \`POST /api/system/reset-data\` at \`server.js:2338\`**
   - Atomic via \`writeJSONAtomic\`.
5. **Legacy Import: \`POST /api/import-data\` at \`server.js:2493\`**
   - Non-atomic via \`writeJSON\`.
6. **Modular Import: \`POST /api/import-data/:section\` at \`server.js:2821\`**
   - Atomic via \`writeJSONAtomic\`.

### Where it's read
- \`GET /api/customers\` (\`server.js:1732\`): Serves customer list to UI.
- \`PUT /api/customers/:id\` (\`server.js:1750\`): Looks up customer to edit.
- \`DELETE /api/customers/:id\` (\`server.js:1761\`): Finds customer to delete.
- \`GET /api/export-data\` (\`server.js:2373\`): Full backup export.
- \`POST /api/import-data\` & \`:section\` (\`server.js:2473\`, \`2594\`): Pre-import backup read.
- \`GET /api/stats\` (\`server.js:5424\`): Total customer count calculation.

### Full lifecycle
- **CREATE**: Created independently.
- **UPDATE**: Updates profile fields.
- **DELETE**: Hard delete (\`splice\`). Does NOT cascade to invoices; existing invoices preserve customer data snapshot.
- **Audit Logging**: Customer mutations do not emit entries to \`manufacturing_audit.json\`.

### Cross-file transactions
Single-store operations. No multi-file transactional participation.

### Known edge cases / validation gaps
- **Non-Atomic Writes**: Create and update use direct synchronous \`writeJSON\` instead of atomic tmp-rename.
- **No Referential Integrity Check on Delete**: Deleting a customer whose ID is referenced in open invoices is permitted without warnings.

---

## recipes.json

### Schema
- Top-level Container: Object with keys:
  - \`recipes\`: Array of Recipe records (Required)
  - \`lastUpdated\`: String ISO 8601 timestamp (Required)
- Record Fields:
  - \`id\`: String (Required). Primary Key. Format: \`REC-XXXXXX\` via \`uid('REC')\`.
  - \`name\`: String (Required). Formula name. Validated non-empty at \`server.js:3832\`.
  - \`productId\`: String (Optional). Foreign Key referencing \`products.json\`.
  - \`productName\`: String (Optional). Denormalized product name.
  - \`output_qty\`: Number (Required). Yield quantity produced per batch (Float > 0).
  - \`output_unit\`: String (Required). Yield unit (\`'kg'\`, \`'g'\`, \`'L'\`, \`'mL'\`).
  - \`ingredients\`: Array of Ingredient records (Required, non-empty):
    - \`rawMaterialId\`: String (Required). Foreign Key referencing \`raw_materials.json\`.
    - \`name\`: String (Optional). Denormalized material name.
    - \`quantity\`: Number (Required). Material quantity required per formula batch.
    - \`unit\`: String (Required). Measurement unit. Must match raw material unit.
    - \`percentage\`: Number (Optional). Formula proportion percentage.
    - \`vendorPreference\`: Object (Optional):
      - \`mode\`: String (\`'FIFO'\` | \`'VENDOR'\`).
      - \`vendorId\`: String | null.
      - \`vendorName\`: String | null.
  - \`stages\`: Array of Strings / Objects (Optional). SOP process instructions.
  - \`notes\`: String (Optional).
  - \`createdAt\`: String (Required). ISO 8601 timestamp.
  - \`updatedAt\`: String (Required). ISO 8601 timestamp.
- Foreign Keys / References:
  - References \`raw_materials.json\` (\`ingredients[].rawMaterialId\`): Validated at recipe creation/update (\`server.js:3843\`, \`3905\`). Blocks RM deletion if referenced.
  - References \`products.json\` (\`productId\`): Back-linked during startup sync (\`server.js:538\`).
  - Inward reference from \`manufacturing_batches.json\` (\`recipeId\`): Identifies formulation executed.
  - Inward reference from \`finished_goods.json\` (\`recipeId\`): Identifies bulk product formula.

### Where it's written
1. **Startup Reconciler: \`reconcileFinishedGoodsAndProducts()\` at \`server.js:598\`**
   - Synchronizes \`productId\` back-links between recipes and finished goods.
   - **Atomicity**: Atomic via \`writeJSONAtomic\`.
2. **Product Deletion Cascade: \`DELETE /api/products/:id\` at \`server.js:869\`**
   - Clears \`recipe.productId\` when linked product is deleted.
   - **Atomicity**: Atomic via \`writeJSONAtomic\`.
3. **System Reset: \`POST /api/system/reset-data\` at \`server.js:2341\`**
   - Clears collection.
   - **Atomicity**: Atomic via \`writeJSONAtomic\`.
4. **Legacy Import: \`POST /api/import-data\` at \`server.js:2502\`**
   - Non-atomic via \`writeJSON\`.
5. **Modular Import: \`POST /api/import-data/:section\` at \`server.js:2740\`**
   - Atomic via \`writeJSONAtomic\`.
6. **Create Recipe: \`POST /api/recipes\` at \`server.js:3885\`**
   - Saves new recipe, creates initial version in \`recipe_history.json\`.
   - **Atomicity**: Atomic via \`writeJSONAtomic\`.
7. **Update Recipe: \`PUT /api/recipes/:id\` at \`server.js:3959\`**
   - Updates recipe formulation, pushes revision snapshot to \`recipe_history.json\`.
   - **Atomicity**: Atomic via \`writeJSONAtomic\`.
8. **Delete Recipe: \`DELETE /api/recipes/:id\` at \`server.js:3992\`**
   - Spliced from array. Cascades: clears \`product.recipeId\` in \`products.json\` and \`fg.recipeId\` in \`finished_goods.json\`.
   - **Atomicity**: Atomic via \`writeJSONAtomic\`.

### Where it's read
- \`reconcileFinishedGoodsAndProducts()\` (\`server.js:487\`): Startup reconciliation.
- \`GET /api/recipes\` (\`server.js:3822\`): Serves recipe list.
- \`PUT /api/recipes/:id\` (\`server.js:3890\`): Validates recipe exists.
- \`GET /api/recipes/:id/history\` (\`server.js:3964\`): Checks recipe existence.
- \`DELETE /api/recipes/:id\` (\`server.js:3982\`): Finds recipe to delete.
- \`POST /api/manufacturing-batches/preview\` (\`server.js:4023\`): Reads formula ingredients to calculate batch material requirements.
- \`POST /api/manufacturing-batches/commit\` (\`server.js:4241\`): Reads formula for stock allocation and deduction.
- \`GET /api/context\` (\`server.js:5377\`): AI context summary.

### Full lifecycle
- **CREATE**: Created via \`POST /api/recipes\`. Automatically creates version 1 in \`recipe_history.json\` (\`server.js:3928\`).
- **UPDATE**: Updated via \`PUT /api/recipes/:id\`. Pushes new incremented version snapshot to \`recipe_history.json\`.
- **DELETE**: Hard delete (\`splice\`). Cascades: clears \`product.recipeId\` in \`products.json\` (\`server.js:4001\`) and \`fg.recipeId\` in \`finished_goods.json\` (\`server.js:4009\`).
- **Audit Logging**: Does not write to \`manufacturing_audit.json\`; revision tracking is handled exclusively by \`recipe_history.json\`.

### Cross-file transactions
Recipe creation and updates write \`recipes.json\` and \`recipe_history.json\` sequentially without a transaction. Recipe deletion writes \`recipes.json\`, \`products.json\`, and \`finished_goods.json\`.

### Known edge cases / validation gaps
- **No Lock on Production Allocation**: A recipe can be deleted while a manufacturing batch preview is open in UI. If the user subsequently commits, the commit handler re-checks recipe existence (\`server.js:4242\`) and rejects with HTTP 404, preventing corrupt commits.

---

## recipe_history.json

### Schema
- Top-level Container: Object with keys:
  - \`recipe_history\`: Array of Recipe History snapshots (Required)
  - \`lastUpdated\`: String ISO 8601 timestamp (Required)
- Record Fields:
  - \`id\`: String (Required). Primary Key. Format: \`RH-XXXXXX\` via \`uid('RH')\`.
  - \`recipeId\`: String (Required). References \`recipes.json\`.
  - \`version\`: Number (Required). Sequential integer version (1, 2, 3...).
  - \`snapshot\`: Object (Required). Deep JSON clone of the complete recipe object at that revision.
  - \`changedBy\`: String (Optional, default \`'User'\`).
  - \`changeSummary\`: String (Optional). Text describing alterations.
  - \`timestamp\`: String (Required). ISO 8601 timestamp.
- Foreign Keys / References:
  - References \`recipes.json\` (\`recipeId\`).

### Where it's written
1. **Audit Ledgers Purge: \`DELETE /api/audit-ledgers\` at \`server.js:2273\`**
   - Clears history array to \`[]\`.
   - **Atomicity**: Atomic via \`writeJSONAtomic\`.
2. **System Reset: \`POST /api/system/reset-data\` at \`server.js:2342\`**
   - Clears history array.
   - **Atomicity**: Atomic via \`writeJSONAtomic\`.
3. **Recipe Creation & Modification: \`POST /api/recipes\` & \`PUT /api/recipes/:id\` at \`server.js:3928\`**
   - Appends snapshot with calculated version number:
     \`\`\`javascript
     // server.js:3918-3927
     const prevVersions = (historyData.recipe_history || []).filter(h => h.recipeId === recipe.id);
     const nextVersion = prevVersions.length + 1;
     historyData.recipe_history.push({
       id: uid('RH'),
       recipeId: recipe.id,
       version: nextVersion,
       snapshot: JSON.parse(JSON.stringify(recipe)),
       timestamp: new Date().toISOString(),
       changeSummary: isNew ? 'Initial recipe creation' : 'Recipe updated'
     });
     \`\`\`
   - **Atomicity**: Atomic via \`writeJSONAtomic\`.

### Where it's read
- \`GET /api/recipes/:id/history\` (\`server.js:3968\`): Returns revision timeline for a recipe.
- \`GET /api/export-data\` (\`server.js:2378\`): Full backup export.
- \`POST /api/import-data\` (\`server.js:2477\`): Pre-import backup read.

### Full lifecycle
- **CREATE**: Appended on recipe create and update.
- **UPDATE**: Immutable; entries are never updated.
- **DELETE**: Wiped completely on \`DELETE /api/audit-ledgers\` or factory reset. Deleting a parent recipe does **not** purge its history records, preserving audit trail.

### Cross-file transactions
Written alongside \`recipes.json\` during create and update.

### Known edge cases / validation gaps
- **Purge via Clear Audit**: \`DELETE /api/audit-ledgers\` wipes \`recipe_history.json\`, even though recipe history represents engineering versioning rather than operational inventory logs.

---
`);
};
