const fs = require('fs');

module.exports = function(append) {
  append(`## Full Transaction Map

| Operation | Endpoint / Hook | Files Written (in order) | Files Read | Audit Event Logged | Reversible? (Y/N + how) |
| :--- | :--- | :--- | :--- | :--- | :--- |
| **Startup Invariant Reconciliation** | \`server.js:261\` (\`reconcileRawMaterialBatches\`) | 1. \`raw_material_batches.json\`<br>2. \`raw_materials.json\` | \`raw_materials.json\`, \`raw_material_batches.json\` | None (silent invariant repair) | **N** (Overwrites baseline stock) |
| **Startup Bulk & Product Reconciliation** | \`server.js:484\` (\`reconcileFinishedGoodsAndProducts\`) | 1. \`finished_goods.json\`<br>2. \`recipes.json\`<br>3. \`products.json\` | \`finished_goods.json\`, \`recipes.json\`, \`products.json\`, \`manufacturing_batches.json\` | None | **N** (Syncs product bulkStock to FG) |
| **Startup Audit Normalization & Hashing** | \`server.js:613\` (\`reconcileAuditHashChain\`) | 1. \`manufacturing_audit.json\` | \`manufacturing_audit.json\` | None (auto-heals SHA-256 chain) | **N** (Re-hashes invalid blocks) |
| **Create Raw Material** | \`POST /api/raw-materials\` (\`server.js:2969\`) | 1. \`raw_materials.json\`<br>2. \`raw_material_batches.json\`<br>3. \`raw_material_transactions.json\`<br>4. \`manufacturing_audit.json\` | \`raw_materials.json\` | \`INVENTORY_IN\` (if opening stock > 0) | **Y** (Via \`DELETE /api/raw-materials/:id\` if not referenced) |
| **Edit Raw Material** | \`PUT /api/raw-materials/:id\` (\`server.js:3102\`) | 1. \`raw_materials.json\`<br>2. \`raw_material_batches.json\`<br>3. \`manufacturing_audit.json\` | \`raw_materials.json\`, \`raw_material_batches.json\` | \`INVENTORY_ADJUSTMENT\` | **Y** (Re-edit with previous values) |
| **Delete Raw Material** | \`DELETE /api/raw-materials/:id\` (\`server.js:3164\`) | 1. \`manufacturing_audit.json\`<br>2. \`raw_materials.json\`<br>3. \`raw_material_batches.json\` | \`raw_materials.json\`, \`recipes.json\`, \`products.json\`, \`manufacturing_batches.json\` | \`DATA_DELETION\` | **N** (Hard delete; child batches purged) |
| **Inward Purchase / Add Stock** | \`POST /api/raw-materials/:id/add-stock\` (\`server.js:3312\`) | 1. \`raw_materials.json\`<br>2. \`raw_material_batches.json\`<br>3. \`raw_material_transactions.json\`<br>4. \`manufacturing_audit.json\` | \`raw_materials.json\`, \`raw_material_batches.json\` | \`INVENTORY_IN\` | **Y** (Purge vendor lots via \`delete-vendor\` or manual stock adjustment) |
| **Purge Vendor Lots** | \`POST /api/raw-materials/:id/delete-vendor\` (\`server.js:3576\`) | 1. \`raw_material_batches.json\`<br>2. \`raw_materials.json\`<br>3. \`manufacturing_audit.json\` | \`raw_materials.json\`, \`raw_material_batches.json\` | \`DATA_DELETION\` | **N** (Vendor lots spliced; stock subtracted) |
| **Direct Batch Creation** | \`POST /api/raw-materials/:id/batches\` (\`server.js:3767\`) | 1. \`raw_material_batches.json\` | \`raw_materials.json\`, \`raw_material_batches.json\` | None | **N** (Direct append) |
| **Create Recipe BOM** | \`POST /api/recipes\` (\`server.js:3827\`) | 1. \`recipes.json\`<br>2. \`recipe_history.json\` | \`recipes.json\`, \`raw_materials.json\` | None (\`recipe_history\` logged) | **Y** (Via \`DELETE /api/recipes/:id\`) |
| **Edit Recipe BOM** | \`PUT /api/recipes/:id\` (\`server.js:3889\`) | 1. \`recipe_history.json\`<br>2. \`recipes.json\` | \`recipes.json\`, \`raw_materials.json\`, \`recipe_history.json\` | None (\`recipe_history\` version incremented) | **Y** (Rollback from \`recipe_history.json\` snapshot) |
| **Delete Recipe BOM** | \`DELETE /api/recipes/:id\` (\`server.js:3981\`) | 1. \`recipes.json\`<br>2. \`products.json\`<br>3. \`finished_goods.json\`<br>4. \`manufacturing_audit.json\` | \`recipes.json\`, \`products.json\`, \`finished_goods.json\` | \`DATA_DELETION\` | **N** (Hard delete; recipe history preserved) |
| **Manufacturing Batch Preview** | \`POST /api/manufacturing-batches/preview\` (\`server.js:4212\`) | None (Read-only simulation) | \`recipes.json\`, \`raw_materials.json\`, \`raw_material_batches.json\` | None | N/A (Simulation) |
| **Manufacturing Batch Commit** | \`POST /api/manufacturing-batches/commit\` (\`server.js:4236\`) | 1. \`products.json\`<br>2. \`raw_materials.json\`<br>3. \`raw_material_transactions.json\`<br>4. \`raw_material_batches.json\`<br>5. \`finished_goods.json\`<br>6. \`finished_goods_transactions.json\`<br>7. \`manufacturing_batches.json\`<br>8. \`manufacturing_audit.json\` | \`recipes.json\`, \`raw_materials.json\`, \`raw_material_batches.json\`, \`finished_goods.json\`, \`products.json\` | \`BATCH_CREATION\` | **N** (No automated un-commit; ingredients consumed) |
| **Delete Manufacturing Batch** | \`DELETE /api/manufacturing-batches/:id\` (\`server.js:5329\`) | 1. \`manufacturing_batches.json\`<br>2. \`finished_goods.json\`<br>3. \`manufacturing_audit.json\` | \`manufacturing_batches.json\`, \`finished_goods.json\` | \`DATA_DELETION\` | **N** (Metadata deleted; consumed lots remain deducted) |
| **Delete Bulk Finished Good** | \`DELETE /api/finished-goods/:id\` (\`server.js:5269\`) | 1. \`finished_goods.json\`<br>2. \`products.json\`<br>3. \`manufacturing_audit.json\` | \`finished_goods.json\`, \`products.json\` | \`DATA_DELETION\` | **N** (Hard delete; bulkStock reset to 0) |
| **Create Product Catalog** | \`POST /api/products\` (\`server.js:675\`) | 1. \`products.json\`<br>2. \`manufacturing_audit.json\` | \`products.json\` | \`CATALOG_CREATE\` | **Y** (Via \`DELETE /api/products/:id\`) |
| **Edit Product Catalog** | \`PUT /api/products/:id\` (\`server.js:746\`) | 1. \`products.json\` | \`products.json\` | None | **Y** (Re-edit with previous values) |
| **Delete Product Catalog** | \`DELETE /api/products/:id\` (\`server.js:849\`) | 1. \`manufacturing_audit.json\`<br>2. \`products.json\`<br>3. \`recipes.json\`<br>4. \`finished_goods.json\` | \`products.json\`, \`recipes.json\`, \`finished_goods.json\` | \`DATA_DELETION\` | **N** (Hard delete; unlinks recipe and FG) |
| **Packaging Deletion Impact Preview** | \`GET .../variants/:variantId/deletion-impact\` (\`server.js:902\`) | None (Read-only impact analysis) | \`products.json\`, \`raw_material_transactions.json\`, \`raw_materials.json\` | None | N/A (Simulation) |
| **Delete Variant (REVERSE)** | \`DELETE .../variants/:variantId\` (\`server.js:984\`) | 1. \`raw_materials.json\`<br>2. \`raw_material_batches.json\`<br>3. \`raw_material_transactions.json\`<br>4. \`products.json\`<br>5. \`manufacturing_audit.json\` | \`products.json\`, \`raw_material_transactions.json\`, \`raw_material_batches.json\`, \`raw_materials.json\` | \`TRANSACTION_REVERSAL\`, \`INVENTORY_IN\`, \`DATA_DELETION\` | **N** (Unwinds allocations; variant spliced permanently) |
| **Delete Variant (DISCARD)** | \`DELETE .../variants/:variantId\` (\`server.js:984\`) | 1. \`products.json\`<br>2. \`manufacturing_audit.json\` | \`products.json\` | \`INVENTORY_ADJUSTMENT\`, \`DATA_DELETION\` | **N** (Stock written off; variant spliced) |
| **Bottling / Packaging Run** | \`POST /api/products/:id/fill-bottles\` (\`server.js:1256\`) | 1. \`products.json\`<br>2. \`raw_materials.json\`<br>3. \`raw_material_batches.json\`<br>4. \`raw_material_transactions.json\`<br>5. \`manufacturing_audit.json\`<br>6. \`finished_goods.json\`<br>7. \`finished_goods_transactions.json\` | \`products.json\`, \`finished_goods.json\`, \`raw_materials.json\`, \`raw_material_batches.json\` | \`INVENTORY_OUT\` (packaging & bulk) | **Y** (Partially reversible via variant deletion \`REVERSE\`) |
| **Manual Variant Stock Update** | \`POST /api/products/:id/update-variant-stock\` (\`server.js:1577\`) | 1. \`finished_goods.json\`<br>2. \`finished_goods_transactions.json\`<br>3. \`products.json\` | \`products.json\`, \`finished_goods.json\` | None | **Y** (Manual re-adjustment) |
| **Create Customer** | \`POST /api/customers\` (\`server.js:1737\`) | 1. \`customers.json\` | \`customers.json\` | None | **Y** (Via \`DELETE /api/customers/:id\`) |
| **Edit Customer** | \`PUT /api/customers/:id\` (\`server.js:1748\`) | 1. \`customers.json\` | \`customers.json\` | None | **Y** (Re-edit) |
| **Delete Customer** | \`DELETE /api/customers/:id\` (\`server.js:1759\`) | 1. \`customers.json\` | \`customers.json\` | None | **N** (Hard delete) |
| **Create Sales Invoice** | \`POST /api/invoices\` (\`server.js:1792\`) | 1. \`finished_goods_transactions.json\`<br>2. \`products.json\`<br>3. \`manufacturing_audit.json\`<br>4. \`invoices.json\` | \`invoices.json\`, \`products.json\`, \`settings.json\` | \`INVENTORY_OUT\` | **Y** (Cancel with \`restock=true\`) |
| **Update Invoice** | \`PUT /api/invoices/:id\` (\`server.js:2096\`) | 1. \`invoices.json\` | \`invoices.json\` | None | **Y** (Re-edit status) |
| **Cancel Invoice (No Restock)** | \`DELETE /api/invoices/:id\` (\`server.js:2158\`) | 1. \`invoices.json\` | \`invoices.json\` | None | **N** (Soft delete: status marked \`'cancelled'\`) |
| **Cancel Invoice (Restock)** | \`DELETE /api/invoices/:id?restock=true\` (\`server.js:2158\`) | 1. \`finished_goods.json\`<br>2. \`finished_goods_transactions.json\`<br>3. \`products.json\`<br>4. \`invoices.json\` | \`invoices.json\`, \`products.json\`, \`finished_goods.json\` | None | **N** (Stock restored to variants; status \`'cancelled'\`) |
| **Clear All Audit Ledgers** | \`DELETE /api/audit-ledgers\` (\`server.js:2268\`) | 1. \`raw_material_transactions.json\`<br>2. \`finished_goods_transactions.json\`<br>3. \`manufacturing_audit.json\`<br>4. \`recipe_history.json\` | None | None (wipes all audit memory) | **N** (Permanent wipe; resets hash chain) |
| **Update Settings** | \`PUT /api/settings\` (\`server.js:2285\`) | 1. \`settings.json\` | \`settings.json\` | None | **Y** (Re-edit) |
| **Factory System Reset** | \`POST /api/system/reset-data\` (\`server.js:2293\`) | 1. \`settings.json\`<br>2. \`products.json\`<br>3. \`customers.json\`<br>4. \`invoices.json\`<br>5. \`raw_materials.json\`<br>6. \`recipes.json\`<br>7. \`recipe_history.json\`<br>8. \`manufacturing_batches.json\`<br>9. \`manufacturing_audit.json\`<br>10. \`finished_goods.json\`<br>11. \`raw_material_transactions.json\`<br>12. \`raw_material_batches.json\`<br>13. \`finished_goods_transactions.json\`<br>14. \`notes.json\`<br>15. \`data/.version\` | None | None | **N** (Wipes all 14 stores + backup files) |
| **Legacy Data Import** | \`POST /api/import-data\` (\`server.js:2417\`) | 1. \`pre_import_backup.json\`<br>2. \`settings.json\`<br>3. \`products.json\`<br>4. \`customers.json\`<br>5. \`invoices.json\`<br>6. \`raw_materials.json\`<br>7. \`recipes.json\`<br>8. \`manufacturing_batches.json\`<br>9. \`finished_goods.json\`<br>10. \`raw_material_transactions.json\`<br>11. \`finished_goods_transactions.json\` | All operational stores | None | **Y** (Restore from \`pre_import_backup.json\`) |
| **Modular Section Import** | \`POST /api/import-data/:section\` (\`server.js:2540\`) | 1. \`pre_import_backup_*.json\`<br>2. Targeted section store(s) | Targeted section store(s) | None | **Y** (Restore from timestamped backup) |
| **Audit Verification** | \`GET /api/manufacturing-audit/verify\` (\`server.js:4743\`) | None (Read-only cryptographic check) | \`manufacturing_audit.json\` | None | N/A (Verification) |
| **Save Scratchpad Notes** | \`POST /api/notes\` (\`server.js:5535\`) | 1. \`notes.json\` | None | None | **Y** (Overwritten by typing) |

---
`);
};
