const fs = require('fs');

module.exports = function(append) {
  append(`## manufacturing_batches.json

### Schema
- Top-level Container: Object with keys:
  - \`manufacturing_batches\`: Array of Manufacturing Batch records (Required)
  - \`lastUpdated\`: String ISO 8601 timestamp (Required)
- Record Fields:
  - \`id\`: String (Required). Primary Key. Format: \`MFG-YYYYMMDD-NNNNN\` (date string + 5-digit random integer). Generated by:
    \`\`\`javascript
    // server.js:207-214
    function generateMfgId() {
      const d = new Date();
      const dateStr = d.getFullYear() +
        String(d.getMonth() + 1).padStart(2, '0') +
        String(d.getDate()).padStart(2, '0');
      const rand = String(Math.floor(Math.random() * 90000) + 10000);
      return \`MFG-\${dateStr}-\${rand}\`;
    }
    \`\`\`
  - \`mfgId\`: String (Required alias). Exact match of \`id\`.
  - \`recipeId\`: String (Required). Foreign Key referencing \`recipes.json\`.
  - \`recipeName\`: String (Optional). Denormalized formula name.
  - \`productId\`: String (Optional). Foreign Key referencing \`products.json\`.
  - \`productName\`: String (Optional). Denormalized product name.
  - \`batchSize\`: Number (Required). Batch multiplier (Float > 0, e.g. 1, 2.5, 10).
  - \`batchNumber\`: String (Optional). User/plant specified lot designation.
  - \`outputQuantity\`: Number (Required). Calculated manufactured yield: \`batchSize * recipe.output_qty\`.
  - \`outputUnit\`: String (Required). Yield unit from recipe (\`kg\`, \`g\`, \`L\`, \`mL\`).
  - \`materialsConsumed\`: Array of Objects (Required). Audit breakdown of consumed raw material lots:
    \`\`\`json
    [
      {
        "rawMaterialId": "RM-179017-ABC",
        "rawMaterialName": "Sugar",
        "quantity": 10,
        "unit": "kg",
        "cost": 400,
        "allocations": [
          { "batchId": "RMB-2026-0001", "supplierBatchNumber": "LOT-1", "quantity": 10, "unitCost": 40 }
        ]
      }
    ]
    \`\`\`
  - \`totalMaterialCost\`: Number (Optional). Sum of all consumed ingredients cost.
  - \`costPerUnit\`: Number (Optional). \`totalMaterialCost / outputQuantity\`.
  - \`status\`: String (Required, default \`'COMPLETED'\`).
  - \`auditCorrelationId\`: String (Required). Format \`AUD-YYYY-NNNNNN\`.
  - \`notes\`: String (Optional).
  - \`operatorName\`: String (Optional, default \`'Plant Operator'\`).
  - \`manufacturingDate\`: String (Optional). Execution date.
  - \`createdAt\`: String (Required). ISO 8601 timestamp.
  - \`updatedAt\`: String (Optional). ISO 8601 timestamp.
- Foreign Keys / References:
  - References \`recipes.json\` (\`recipeId\`): Validated at commit (\`server.js:4242\`).
  - References \`products.json\` (\`productId\`): Identified from recipe or catalog.
  - References \`raw_materials.json\` (\`materialsConsumed[].rawMaterialId\`).
  - References \`raw_material_batches.json\` (\`materialsConsumed[].allocations[].batchId\`).
  - Inward reference from \`finished_goods.json\` (\`manufacturingBatchId\`): Links bulk inventory to this production run.

### Where it's written
1. **System Reset: \`POST /api/system/reset-data\` at \`server.js:2343\`**
   - Clears collection.
   - **Atomicity**: Atomic via \`writeJSONAtomic\`.
2. **Legacy Import: \`POST /api/import-data\` at \`server.js:2505\`**
   - Overwrites array.
   - **Atomicity**: Non-atomic via \`writeJSON\` (\`fs.writeFileSync\`).
3. **Modular Import: \`POST /api/import-data/:section\` at \`server.js:2885\`**
   - Merges manufacturing batches.
   - **Atomicity**: Atomic via \`writeJSONAtomic\`.
4. **Manufacturing Commit: \`POST /api/manufacturing-batches/commit\` at \`server.js:4657\`**
   - **Trigger**: Plant operator commits a manufactured batch.
   - **Fields Changed**: Pushes new batch object with complete lot allocation breakdown.
   - **Atomicity**: Atomic via \`writeJSONAtomic\`. **Not protected by \`withInventoryLock\`**.
5. **Delete Manufacturing Batch: \`DELETE /api/manufacturing-batches/:id\` at \`server.js:5340\`**
   - **Trigger**: User deletes batch record from history.
   - **Fields Changed**: Spliced from array. Cascades: clears \`manufacturingBatchId\` in \`finished_goods.json\` (\`server.js:5353\`).
   - **Atomicity**: Atomic via \`writeJSONAtomic\`.

### Where it's read
- \`reconcileFinishedGoodsAndProducts()\` (\`server.js:489\`): Matches orphaned finished goods to recipe IDs.
- \`DELETE /api/raw-materials/:id\` (\`server.js:3168\`): Dependency check blocking RM deletion if referenced by active batches.
- \`GET /api/raw-material-batches/:id/traceability\` (\`server.js:3683\`): Downstream lineage tracing.
- \`GET /api/manufacturing-batches\` (\`server.js:4667\`): Serves batch list to UI.
- \`GET /api/manufacturing-batches/:id/traceability\` (\`server.js:4674\`): Full 360-degree traceability map (recipe $\\rightarrow$ raw material lots $\\rightarrow$ finished goods $\\rightarrow$ sales invoices).
- \`DELETE /api/manufacturing-batches/:id\` (\`server.js:5331\`): Validates batch exists before deletion.
- \`GET /api/stats\` (\`server.js:5426\`): Computes total completed batches.

### Full lifecycle
- **CREATE**: Created strictly upon committing production via \`POST /api/manufacturing-batches/commit\`.
- **UPDATE**: Immutable post-creation. No update endpoint exists.
- **DELETE**: Hard delete (\`splice\`). Deleting a batch removes the audit summary from this store and clears foreign keys in \`finished_goods.json\`, but does **not** restore the consumed raw materials or delete the produced finished goods.
- **Audit Logging**: Commit logs \`BATCH_CREATION\` to \`manufacturing_audit.json\` (\`server.js:4658\`). Batch deletion logs \`DATA_DELETION\` (\`server.js:629\`).

### Cross-file transactions
Participates in manufacturing commit across 8 stores (\`products\`, \`raw_materials\`, \`raw_material_transactions\`, \`raw_material_batches\`, \`finished_goods\`, \`finished_goods_transactions\`, \`manufacturing_batches\`, \`manufacturing_audit\`).

### Known edge cases / validation gaps
- **No Reverse/Undo on Batch Deletion**: Deleting a manufacturing batch via \`DELETE /api/manufacturing-batches/:id\` does not restore consumed ingredient lots, nor does it decrement the produced finished goods bulk pool. It is purely a metadata deletion.

---

## manufacturing_audit.json

### Schema
- Top-level Container: Object with keys:
  - \`manufacturing_audit\`: Array of AuditEntry records (Required)
  - \`lastUpdated\`: String ISO 8601 timestamp (Required)
- Record Fields:
  - \`auditId\`: String (Required). Primary Key. Format: \`AUD-YYYY-NNNNNN\`. Generated by:
    \`\`\`javascript
    // server.js:217-241
    function generateAuditCorrelationId() {
      const year = new Date().getFullYear();
      const prefix = \`AUD-\${year}-\`;
      const mfgAudit = readJSON(MANUFACTURING_AUDIT_FILE) || { manufacturing_audit: [] };
      const rmTxns = readJSON(RAW_MAT_TXN_FILE) || { raw_material_transactions: [] };
      let maxSeq = 0;
      const checkId = (id) => {
        if (typeof id === 'string' && id.startsWith(prefix)) {
          const numPart = parseInt(id.replace(prefix, ''), 10);
          if (!isNaN(numPart) && numPart > maxSeq) maxSeq = numPart;
        }
      };
      (mfgAudit.manufacturing_audit || []).forEach(r => {
        checkId(r.auditCorrelationId);
        checkId(r.auditId);
      });
      (rmTxns.raw_material_transactions || []).forEach(r => {
        checkId(r.auditCorrelationId);
      });
      return \`\${prefix}\${String(maxSeq + 1).padStart(6, '0')}\`;
    }
    \`\`\`
  - \`auditCorrelationId\`: String (Required alias). Shared correlation ID grouping multi-store events.
  - \`hash\`: String (Required). SHA-256 cryptographic hash of this record and its predecessor. Generated by:
    \`\`\`javascript
    // server.js:128-141
    function computeAuditHash(entry, precedingHash) {
      const norm = {
        auditCorrelationId: entry.auditCorrelationId || entry.auditId || '',
        eventType: entry.eventType || entry.action || '',
        category: entry.category || '',
        entityType: entry.entityType || '',
        entityId: entry.entityId || '',
        entityName: entry.entityName || '',
        quantity: entry.quantity !== undefined && entry.quantity !== null ? Number(entry.quantity) : null,
        timestamp: entry.timestamp || '',
        precedingHash: precedingHash || 'GENESIS'
      };
      return crypto.createHash('sha256').update(JSON.stringify(norm)).digest('hex');
    }
    \`\`\`
  - \`precedingHash\`: String (Required). Hash of the prior entry, or \`'GENESIS'\` for first block.
  - \`immutable\`: Boolean (Required, \`true\`).
  - \`eventType\`: String (Required). Values: \`'INVENTORY_IN'\`, \`'INVENTORY_OUT'\`, \`'INVENTORY_ADJUSTMENT'\`, \`'BATCH_CREATION'\`, \`'TRANSACTION_REVERSAL'\`, \`'DATA_DELETION'\`, \`'CATALOG_CREATE'\`, \`'DEPENDENCY_BLOCK'\`.
  - \`category\`: String (Required, e.g. \`'INVENTORY'\`, \`'MANUFACTURING'\`, \`'REVERSALS'\`, \`'DELETIONS'\`, \`'CATALOG'\`).
  - \`entityType\`: String (Required, e.g. \`'RAW_MATERIAL'\`, \`'PRODUCT'\`, \`'PRODUCT_VARIATION'\`, \`'RECIPE'\`, \`'MANUFACTURING_BATCH'\`).
  - \`entityId\`: String (Optional). Primary key of target entity.
  - \`entityName\`: String (Optional). Human-readable label.
  - \`quantity\`: Number | null (Optional).
  - \`unit\`: String (Optional).
  - \`operatorName\`: String (Optional, default \`'Plant Operator'\` or \`'User'\`).
  - \`reason\`: String (Optional). Required on deletions.
  - \`notes\`: String (Optional). Narrative log entry.
  - \`date\`: String (Required, \`YYYY-MM-DD\`).
  - \`time\`: String (Required, \`HH:MM:SS\`).
  - \`timestamp\`: String (Required, ISO 8601).
- Foreign Keys / References:
  - References \`raw_materials.json\` (\`entityId\` when \`entityType === 'RAW_MATERIAL'\`).
  - References \`products.json\` (\`entityId\` when \`entityType === 'PRODUCT'\`).
  - References \`manufacturing_batches.json\` (\`entityId\` when \`entityType === 'MANUFACTURING_BATCH'\`).

### Where it's written
All writes to \`manufacturing_audit.json\` route through \`logAuditEntry(mfgAuditData, entry)\` (\`server.js:143-151\`), which chains SHA-256 hashes:
1. **Startup Reconciler: \`reconcileAuditHashChain()\` at \`server.js:618\`**: Normalizes and self-heals hash chains.
2. **Deletion Audit Helper: \`logDeletionAudit()\` at \`server.js:661\`**: Logs \`DATA_DELETION\` events.
3. **Product Creation: \`POST /api/products\` at \`server.js:739\`**: Logs \`CATALOG_CREATE\`.
4. **Product Deletion: \`DELETE /api/products/:id\` at \`server.js:833\`**: Logs \`DATA_DELETION\`.
5. **Variant Deletion: \`DELETE /api/products/:productId/variants/:variantId\` at \`server.js:1241\`**: Logs \`DATA_DELETION\` and \`TRANSACTION_REVERSAL\`.
6. **Bottling Run: \`POST /api/products/:id/fill-bottles\` at \`server.js:1533\`**: Logs \`INVENTORY_OUT\`.
7. **Invoice Sales Deduction: \`POST /api/invoices\` at \`server.js:2090\`**: Logs \`INVENTORY_OUT\`.
8. **Audit Ledger Wipe: \`DELETE /api/audit-ledgers\` at \`server.js:2272\`**: Resets to \`{ manufacturing_audit: [], lastUpdated: now }\`.
9. **System Reset: \`POST /api/system/reset-data\` at \`server.js:2344\`**: Clears store.
10. **Raw Material Creation: \`POST /api/raw-materials\` at \`server.js:3205\`**: Logs \`INVENTORY_IN\`.
11. **Raw Material Update: \`PUT /api/raw-materials/:id\` at \`server.js:3242\`**: Logs \`INVENTORY_ADJUSTMENT\`.
12. **Raw Material Deletion: \`DELETE /api/raw-materials/:id\` at \`server.js:3278\`**: Logs \`DATA_DELETION\`.
13. **Manufacturing Commit: \`POST /api/manufacturing-batches/commit\` at \`server.js:4658\`**: Logs \`BATCH_CREATION\`.

### Where it's read
- \`generateAuditCorrelationId()\` (\`server.js:221\`): Scans audit IDs to compute next sequence.
- \`reconcileAuditHashChain()\` (\`server.js:615\`): Verifies and recalculates chain hashes on launch.
- \`GET /api/manufacturing-audit/verify\` (\`server.js:4744\`): Cryptographically validates the entire SHA-256 chain from Genesis to tip.
- \`GET /api/manufacturing-audit-ledger\` (\`server.js:4756\`): Serves audit logs to UI.
- \`GET /api/audit-ledger/export\` (\`server.js:5259\`): Exports ledger to Excel (.xlsx) or JSON.

### Full lifecycle
- **CREATE**: Appended automatically upon business transactions via \`logAuditEntry\`.
- **UPDATE**: Strict append-only design. Entries are never updated.
- **DELETE**: Hard delete only during \`DELETE /api/audit-ledgers\` or factory reset. Individual entries cannot be deleted.

### Cross-file transactions
Written at the tail end of nearly all multi-store transactions to record permanent evidence.

### Known edge cases / validation gaps
- **Audit Wipe Contradiction**: The system advertises "tamper-proof immutable audit records", but provides \`DELETE /api/audit-ledgers\` which completely wipes \`manufacturing_audit.json\`, resetting the hash chain back to \`GENESIS\`.
- **Startup Auto-Healing Obscures Tampering**: \`reconcileAuditHashChain()\` automatically normalizes invalid hashes on startup (\`server.js:617-620\`). If an adversary modifies a record offline and restarts the server, the startup reconciler re-hashes from that entry forward, making it valid again unless checked before restart via \`GET /api/manufacturing-audit/verify\`.

---

## finished_goods.json

### Schema
- Top-level Container: Object with keys:
  - \`finished_goods\`: Array of Finished Goods records (Required)
  - \`lastUpdated\`: String ISO 8601 timestamp (Required)
- Record Fields:
  - \`id\`: String (Required). Primary Key. Format: \`FGB-YYYY-NNN\` or \`FG-XXXXXX\` via \`uid('FG')\`.
  - \`productId\`: String (Optional). Foreign Key referencing \`products.json\`.
  - \`productName\`: String (Optional).
  - \`recipeId\`: String (Optional). Foreign Key referencing \`recipes.json\`.
  - \`recipeName\`: String (Optional).
  - \`manufacturingBatchId\`: String (Optional). Foreign Key referencing \`manufacturing_batches.json\`.
  - \`name\`: String (Required). Bulk finished good title.
  - \`currentStock\`: Number (Required). Float. Available bulk volume/weight.
  - \`quantity\`: Number (Optional alias). Synced to \`currentStock\`.
  - \`unit\`: String (Required). Bulk unit (\`kg\`, \`g\`, \`L\`, \`mL\`).
  - \`bottleSize\`: Number (Optional, default 1).
  - \`bottleSizeUnit\`: String (Optional).
  - \`costPerUnit\`: Number (Optional). Production valuation per unit.
  - \`notes\`: String (Optional).
  - \`createdAt\`: String (Required). ISO 8601 timestamp.
  - \`updatedAt\`: String (Optional). ISO 8601 timestamp.
- Foreign Keys / References:
  - References \`products.json\` (\`productId\`).
  - References \`recipes.json\` (\`recipeId\`).
  - References \`manufacturing_batches.json\` (\`manufacturingBatchId\`).

### Where it's written
1. **Startup Sync: \`reconcileFinishedGoodsAndProducts()\` at \`server.js:594\`**
   - Synchronizes \`recipeId\` and \`productId\` references.
   - **Atomicity**: Atomic via \`writeJSONAtomic\`.
2. **Product Deletion Cascade: \`DELETE /api/products/:id\` at \`server.js:877\`**
   - Clears \`fg.productId\` if linked product is deleted.
   - **Atomicity**: Atomic via \`writeJSONAtomic\`.
3. **Bottling Bulk Consumption: \`POST /api/products/:id/fill-bottles\` at \`server.js:1559\`**
   - Deducts consumed bulk:
     \`\`\`javascript
     // server.js:1316-1558
     const bulkNeeded = numBottles * variant.bottleSize; // in base units
     fg.currentStock = Math.max(0, parseFloat((fg.currentStock - bulkDeduction).toFixed(6)));
     \`\`\`
   - **Atomicity**: Protected by \`withInventoryLock\`. Written via \`writeJSONAtomic\`.
4. **Manual Stock Override: \`POST /api/products/:id/update-variant-stock\` at \`server.js:1710\`**
   - Direct stock mutation.
   - **Atomicity**: Atomic via \`writeJSONAtomic\`.
5. **Invoice Cancellation Restock: \`DELETE /api/invoices/:id?restock=true\` at \`server.js:2235\`**
   - Restores bulk stock for legacy unvarianted products.
   - **Atomicity**: Atomic via \`writeJSONAtomic\`.
6. **System Reset: \`POST /api/system/reset-data\` at \`server.js:2345\`**
   - Clears collection.
   - **Atomicity**: Atomic via \`writeJSONAtomic\`.
7. **Legacy Import: \`POST /api/import-data\` at \`server.js:2508\`**
   - Non-atomic via \`writeJSON\` (\`fs.writeFileSync\`).
8. **Modular Import: \`POST /api/import-data/:section\` at \`server.js:2914\`**
   - Atomic via \`writeJSONAtomic\`.
9. **Recipe Deletion Cascade: \`DELETE /api/recipes/:id\` at \`server.js:4009\`**
   - Clears \`fg.recipeId\` if linked recipe deleted.
   - **Atomicity**: Atomic via \`writeJSONAtomic\`.
10. **Manufacturing Commit: \`POST /api/manufacturing-batches/commit\` at \`server.js:4655\`**
    - Pushes new bulk yield record (\`currentStock = outputQuantity\`).
    - **Atomicity**: Atomic via \`writeJSONAtomic\`.
11. **Delete Finished Good: \`DELETE /api/finished-goods/:id\` at \`server.js:5286\`**
    - Hard delete (\`splice\`). Resets linked product \`bulkStock = 0\`.
    - **Atomicity**: Atomic via \`writeJSONAtomic\`.
12. **Manufacturing Batch Deletion Cascade: \`DELETE /api/manufacturing-batches/:id\` at \`server.js:5353\`**
    - Clears \`manufacturingBatchId\` reference.
    - **Atomicity**: Atomic via \`writeJSONAtomic\`.

### Where it's read
- \`reconcileFinishedGoodsAndProducts()\` (\`server.js:486\`): Startup synchronization.
- \`POST /api/products/:id/fill-bottles\` (\`server.js:1283\`): Verifies bulk stock sufficiency before bottling.
- \`DELETE /api/invoices/:id\` (\`server.js:2179\`): Reads stock for restock.
- \`GET /api/finished-goods\` (\`server.js:5264\`): Serves bulk inventory to UI.
- \`DELETE /api/finished-goods/:id\` (\`server.js:5270\`): Finds item to delete.
- \`GET /api/stats\` (\`server.js:5420\`): Calculates bulk inventory valuation.

### Full lifecycle
- **CREATE**: Created upon manufacturing commit.
- **UPDATE**: Decremented upon bottling runs (\`fill-bottles\`).
- **DELETE**: Hard delete (\`splice\`) via \`DELETE /api/finished-goods/:id\`. Clears \`product.bulkStock = 0\` in \`products.json\`.
- **Audit Logging**: Commit logs \`BATCH_CREATION\`. Bottling logs \`INVENTORY_OUT\`. Deletion logs \`DATA_DELETION\`.

### Cross-file transactions
Written in bottling runs (7 files) and manufacturing commits (8 files).

### Known edge cases / validation gaps
- **Stock Squeeze**: If a user runs bottling without linking a recipe, \`fill-bottles\` attempts matching FG by product name or ID; if neither matches, bottling is blocked with HTTP 400.

---

## finished_goods_transactions.json

### Schema
- Top-level Container: Object with keys:
  - \`finished_goods_transactions\`: Array of FG Transactions (Required)
  - \`lastUpdated\`: String ISO 8601 timestamp (Required)
- Record Fields:
  - \`id\`: String (Required). Primary Key. Format: \`FGT-XXXXXX\` via \`uid('FGT')\`.
  - \`transactionId\`: String (Required alias). Format: \`TXN-XXXXXX\` via \`uid('TXN')\`.
  - \`auditCorrelationId\`: String (Required). Format \`AUD-YYYY-NNNNNN\`.
  - \`finishedGoodId\`: String (Optional). References \`finished_goods.json\`.
  - \`productId\`: String (Optional). References \`products.json\`.
  - \`productName\`: String (Optional).
  - \`type\`: String (Required, \`'IN'\` | \`'OUT'\`).
  - \`action\`: String (Required, e.g. \`'Manufacturing Inward'\`, \`'Bottling Deduction'\`, \`'Commercial Invoice'\`).
  - \`quantity\`: Number (Required). Float.
  - \`unit\`: String (Required).
  - \`referenceId\`: String (Optional). Manufacturing batch ID or invoice number.
  - \`date\`: String (Required, \`YYYY-MM-DD\`).
  - \`time\`: String (Required, \`HH:MM:SS\`).
  - \`timestamp\`: String (Required, ISO 8601).
- Foreign Keys / References:
  - References \`finished_goods.json\` (\`finishedGoodId\`).
  - References \`products.json\` (\`productId\`).
  - References \`invoices.json\` (\`referenceId\`).

### Where it's written
1. **Startup Normalizer: \`normalizeHistoricalAuditData()\` at \`server.js:441\`**: Atomic via \`writeJSONAtomic\`.
2. **Bottling Bulk Deduction: \`POST /api/products/:id/fill-bottles\` at \`server.js:1560\`**: Type \`'OUT'\`. Protected by \`withInventoryLock\`.
3. **Manual Stock Adjustment: \`POST /api/products/:id/update-variant-stock\` at \`server.js:1711\`**: Atomic via \`writeJSONAtomic\`.
4. **Invoice Sales Deduction: \`POST /api/invoices\` at \`server.js:1977\`, \`2023\`, \`2065\`**: Type \`'OUT'\`. Protected by \`withInventoryLock\`.
5. **Invoice Cancellation Restock: \`DELETE /api/invoices/:id?restock=true\` at \`server.js:2236\`**: Type \`'IN'\`. Atomic via \`writeJSONAtomic\`.
6. **Audit Ledgers Purge: \`DELETE /api/audit-ledgers\` at \`server.js:2271\`**: Clears array.
7. **System Reset: \`POST /api/system/reset-data\` at \`server.js:2348\`**: Clears array.
8. **Legacy Import: \`POST /api/import-data\` at \`server.js:2517\`**: Non-atomic via \`writeJSON\`.
9. **Manufacturing Commit: \`POST /api/manufacturing-batches/commit\` at \`server.js:4656\`**: Type \`'IN'\`. Atomic via \`writeJSONAtomic\`.

### Where it's read
- \`normalizeHistoricalAuditData()\` (\`server.js:430\`, \`451\`): Startup normalization.
- \`GET /api/raw-material-batches/:id/traceability\` (\`server.js:3686\`): Traceability lineage mapping.
- \`GET /api/manufacturing-batches/:id/traceability\` (\`server.js:4676\`): Lineage mapping.
- \`GET /api/finished-goods-transactions\` (\`server.js:5324\`): Serves FG transaction log to UI.

### Full lifecycle
- **CREATE**: Appended on manufacturing inward, bottling deduction, and commercial invoicing.
- **UPDATE**: Immutable.
- **DELETE**: Wiped on \`DELETE /api/audit-ledgers\` or factory reset.

### Cross-file transactions
Written alongside finished goods, invoices, and manufacturing batches.

### Known edge cases / validation gaps
- **Invoice Double Logging Contradiction**: Invoices deduct strictly from \`variant.stock\`, but \`POST /api/invoices\` still pushes an \`OUT\` transaction to \`finished_goods_transactions.json\` with the line item quantity to preserve historical sales velocity logs.

---
`);
};
